import type { Locale } from "@/lib/i18n/context";

export const navCopy = {
  zh: { home: "首页", about: "关于", products: "产品", contact: "联系", language: "选择语言" },
  "zh-tw": { home: "首頁", about: "關於", products: "產品", contact: "聯絡", language: "選擇語言" },
  en: { home: "Home", about: "About", products: "Products", contact: "Contact", language: "Select language" },
  ja: { home: "ホーム", about: "概要", products: "製品", contact: "連絡", language: "言語を選択" },
  ko: { home: "홈", about: "소개", products: "제품", contact: "연락", language: "언어 선택" },
  fr: { home: "Accueil", about: "À propos", products: "Produits", contact: "Contact", language: "Choisir la langue" },
  de: { home: "Start", about: "Über uns", products: "Produkte", contact: "Kontakt", language: "Sprache wählen" },
  es: { home: "Inicio", about: "Acerca de", products: "Productos", contact: "Contacto", language: "Elegir idioma" },
  ru: { home: "Главная", about: "О нас", products: "Продукты", contact: "Контакты", language: "Выбрать язык" },
  pt: { home: "Início", about: "Sobre", products: "Produtos", contact: "Contato", language: "Escolher idioma" },
};

export const siteCopy = {
  zh: {
    common: {
      productPromise: "产品承诺",
      experienceFlow: "体验流程",
      productIndex: "产品索引",
      operatingPrinciples: "工作原则",
      designPrinciples: "设计原则",
      step: "步骤",
      viewProducts: "查看产品",
      contact: "联系",
      getUpdates: "联系开发者",
      microsoftStore: "Microsoft Store",
      privacy: "隐私政策",
      backToProducts: "返回产品",
    },
    home: {
      eyebrow: "独立 Windows 桌面软件",
      title: "让精力、专注和文件管理回到可控状态。",
      intro: "SoloCraft 汇集 Chicken Fillet 的桌面工具：记录工作精力，降低专注阻力，整理本地文件。每个产品都围绕真实日常使用场景设计，尽量少打扰，多帮你把事情理顺。",
      primary: "了解产品思路",
      secondary: "查看产品",
      currentProduct: "正在展示",
      notes: [
        ["本地优先", "能留在设备上的数据，就不轻易离开设备。"],
        ["低摩擦", "关键动作尽量少步骤，避免把记录、整理和开始专注变成新的负担。"],
        ["桌面原生", "围绕真实 Windows 工作流设计，而不是把网页仪表盘硬塞进桌面。"],
        ["克制表达", "界面服务于理解和行动，不用噪音、徽章和假紧迫感抢注意力。"],
      ],
      chapters: [
        {
          id: "energyflow",
          num: "01 / EnergyFlow",
          title: "看清每一天精力流向。",
          body: "3 秒打卡精力，记录等级、状态、来源与心情。它不是另一张工作量表，而是帮你发现会议、任务和节奏如何影响表现。",
          bullets: ["5 级精力等级", "职场场景", "Pearson + 卡方", "本地隐私优先"],
        },
        {
          id: "deskhaven",
          num: "02 / DeskHaven",
          title: "让混乱桌面重新变成工作台。",
          body: "DeskHaven 是桌面文件避风港：守护每一份文件，让重要内容有一个安静、可控、本地安全的工作台。",
          bullets: ["本地内容空间", "关系图谱", "文件仓", "AES-256"],
        },
        {
          id: "adhd",
          num: "03 / ADHD Focus Timer",
          title: "不惩罚注意力的专注工具。",
          body: "正向计时、呼吸过渡、想法冰箱和全屏专注环境。它不催促你完成任务，而是帮你更温和地进入状态。",
          bullets: ["正向计时", "呼吸引导", "想法冰箱", "本地隐私"],
        },
      ],
      principlesTitle: "少一点干扰，多一点掌控感。",
      principlesBody: "SoloCraft 的产品不追求复杂功能堆叠，而是把一个明确场景做完整：看清精力变化，顺利进入专注，或者把分散文件重新整理成可找回的秩序。",
      productTitle: "选择一个工具，进入对应的工作场景。",
      studioTitle: "小工具，也要经得起长期使用。",
      studioBody: "我更在意产品能否安静地融入日常，而不是第一次打开时有多热闹。真实截图、清晰隐私说明和可验证的功能，比花哨包装更重要。",
      studioNote: "EnergyFlow、DeskHaven 和 ADHD Focus Timer 分别面向精力记录、文件整理和低阻力专注。你可以从任意产品页直接查看功能、截图、隐私说明和下载入口。",
    },
    products: {
      eyebrow: "产品索引",
      title: "选择你现在需要的桌面工具。",
      intro: "每个产品页都展示真实界面、核心功能、隐私说明和下载入口。先看清它解决什么问题，再决定是否安装。",
    },
    productCards: {
      energyflow: {
        title: "EnergyFlow",
        category: "职场能量仪表盘",
        description: "用几秒记录精力、工作状态和恢复来源，再通过趋势与统计看清哪些场景真正消耗你。",
        status: "已推出",
      },
      deskhaven: {
        title: "DeskHaven",
        category: "桌面文件避风港",
        description: "把分散文件放进本地工作台，用档案柜、搜索、关系图谱和备份恢复建立可找回的秩序。",
        status: "已推出",
      },
      adhd: {
        title: "ADHD Focus Timer",
        category: "低压力专注计时器",
        description: "用准备页、呼吸过渡、正向计时和想法冰箱，帮助你更温和地开始并维持一段专注。",
        status: "已推出",
      },
    },
    energyflow: {
      eyebrow: "EnergyFlow / 职场能量仪表盘",
      title: "记录精力变化，看清工作真正消耗在哪里。",
      intro: "EnergyFlow 用几秒完成一次精力记录：等级、工作状态、恢复来源和情绪。积累一段时间后，你可以用趋势和统计结果判断哪些会议、任务或作息正在影响状态。",
      status: "已推出",
      promiseTitle: "不是待办清单，而是你的工作能量记录。",
      promise: "它不评价你是否足够努力，只帮助你把体感变成可回看的记录。长期数据会慢慢呈现：什么让你恢复，什么让你耗竭，哪些安排值得调整。",
      features: [
        ["3 秒打卡", "用最少步骤记录 5 级精力、工作状态、能量来源和心情，不把追踪本身变成负担。"],
        ["深浅模式", "深色模式适合专注，浅色模式适合日间办公。界面保持克制，不用视觉噪音抢走注意力。"],
        ["桌面常驻", "桌面悬浮入口和快捷键让记录可以随手完成：出现、记录、收起，尽量不打断当前工作。"],
        ["统计洞察", "通过 Pearson 相关和卡方检验观察能量与场景之间的关系，用长期记录发现真正的消耗源。"],
        ["隐私保护", "精力状态属于敏感个人数据。EnergyFlow 以本地优先、隐私优先为默认设计方向。"],
      ],
      flow: ["记录当下状态", "积累工作场景", "查看能量趋势", "调整工作节奏"],
    },
    deskhaven: {
      eyebrow: "DeskHaven / 桌面文件避风港",
      title: "把分散文件整理成一个可找回的本地工作台。",
      intro: "DeskHaven 面向 Windows 本地文件整理：把散落的资料、图片、导出文件和项目素材放进可搜索、可归档、可备份的工作空间，并通过关系图谱理解内容之间的连接。",
      status: "已推出",
      promiseTitle: "不是换一个文件夹，而是建立一套本地文件秩序。",
      promise: "文件仓负责归拢和归档，搜索负责快速定位，关系图谱帮助理解内容连接，备份与隐私控制确保重要文件可恢复、可导出、可掌握。",
      features: [
        ["先看全局，再进入细节", "仪表盘汇总文件数量、关系数量、加密状态和存储趋势，让用户第一眼知道桌面内容是否可控。"],
        ["文件仓：把内容放回秩序里", "文件仓集中管理本地文件、元数据和归档状态。它不是云盘，而是本机内容的安静收纳层。"],
        ["关系图谱：看见内容之间的连接", "文件、标签、主题、项目之间的关系可以被看见。用户不只是找文件，也能理解文件为什么重要。"],
        ["隐私与控制权", "密钥、导入导出、加密和控制选项放在清晰位置。重要数据应该由用户掌握。"],
        ["让整理在后台自动发生", "后台自动化、路径、开关和语言设置集中在设置页，整理不应该变成每天必须维护的新系统。"],
      ],
      principles: [
        ["本地优先", "重要文件和索引默认在本机处理。"],
        ["安全可控", "用户必须知道文件在哪里，也能随时导出或找回。"],
        ["关系可视", "文件不是孤立物，项目、标签和内容关系应该可以被理解。"],
        ["低打扰", "整理应该顺手发生，而不是制造新的负担。"],
      ],
    },
    adhd: {
      eyebrow: "ADHD Focus Timer / 低压力专注",
      title: "用更低压力的方式开始一段专注。",
      intro: "ADHD Focus Timer 通过准备页、呼吸过渡、正向计时和想法冰箱，减少开始任务时的阻力。它不把分心当成失败，而是帮你把注意力慢慢带回当前任务。",
      status: "已推出",
      promiseTitle: "专注工具应该降低阻力，而不是增加压力。",
      promise: "正向计时避免倒计时带来的失败感，想法冰箱让突然冒出的念头暂时有地方放，完成反馈记录一次真实投入，而不是给你打分。",
      features: [
        ["进入前先降噪", "介绍弹窗和准备页让用户知道接下来会发生什么，降低开始任务时的心理阻力。"],
        ["准备，而不是逼迫", "时长、白噪音、语言、呼吸引导都在开始前确定，减少专注过程中的额外选择。"],
        ["呼吸过渡", "正式开始前用呼吸引导完成从混乱到专注的切换。"],
        ["正向计时", "计时向前累积，而不是倒数制造失败感。粒子和进度给出轻微陪伴。"],
        ["想法冰箱", "突然冒出的想法不需要立刻处理，可以先放进冰箱，之后再回来。"],
        ["完成反馈", "结束不是审判，而是记录一次真实完成。成就页面给出温和反馈。"],
        ["支持与隐私", "工具保持本地优先、最小数据、清晰隐私说明，避免把专注数据变成另一种压力。"],
      ],
    },
    about: {
      title: "关于 SoloCraft",
      intro: "SoloCraft 是 Chicken Fillet 的独立桌面软件工作室，专注于安静、克制、隐私优先的小工具。",
      story: [
        "我喜欢做那些不抢戏的工具：它们应该在需要时出现，在完成后退到背景里。",
        "EnergyFlow、DeskHaven 和 ADHD Focus Timer 都围绕同一个问题：怎样让桌面工作更可恢复、更可理解、更少压力。",
        "这个网站展示这些工具真实的样子：界面、使用场景、隐私说明和下载方式都尽量清楚，不用夸张包装代替产品本身。",
      ],
      philosophyTitle: "设计原则",
      philosophy: [
        ["小而完整", "每个工具聚焦一个明确场景，但把关键流程做完整。"],
        ["桌面原生", "围绕真实桌面工作流，而不是把网页仪表盘硬塞进应用。"],
        ["克制表达", "视觉服务于理解，不用装饰制造廉价兴奋。"],
        ["隐私优先", "能留在本地的数据，就不轻易离开设备。"],
      ],
      techTitle: "技术方向",
      tech: ["Windows desktop apps", "Local-first storage", "Statistics and visualization", "Privacy-conscious product design"],
      ctaTitle: "想聊产品、合作或反馈？",
      ctaDescription: "我会认真阅读每一封真实来信。",
      ctaButton: "联系我",
    },
    contact: {
      title: "联系",
      intro: "产品反馈、合作想法、媒体询问或单纯打个招呼，都可以发邮件给我。",
      infoTitle: "联系方式",
      email: "邮箱",
    },
    footer: {
      subtitle: "Chicken Fillet 的独立桌面软件工作室。",
      studio: "工作室",
      products: "产品",
      legal: "法务",
      about: "关于",
      contact: "联系",
      privacy: "隐私政策",
      copyright: "安静、克制、隐私优先的桌面工具。",
    },
  },
  en: {
    common: {
      productPromise: "Product promise",
      experienceFlow: "Experience flow",
      productIndex: "Product index",
      operatingPrinciples: "Operating principles",
      designPrinciples: "Design principles",
      step: "Step",
      viewProducts: "View products",
      contact: "Contact",
      getUpdates: "Contact developer",
      microsoftStore: "Microsoft Store",
      privacy: "Privacy policy",
      backToProducts: "Back to products",
    },
    home: {
      eyebrow: "Independent Windows desktop software",
      title: "Regain control of energy, focus, and local files.",
      intro: "SoloCraft brings together Chicken Fillet's desktop tools for tracking work energy, reducing focus friction, and organizing local files. Each product is built around real daily workflows, with less noise and more control.",
      primary: "Explore the approach",
      secondary: "View products",
      currentProduct: "Now showing",
      notes: [
        ["Local-first", "Data that can stay on your device should not leave it casually."],
        ["Low-friction", "Important actions stay short, so tracking, organizing, and starting focus do not become new chores."],
        ["Desktop-native", "Designed around real Windows workflows, not a web dashboard squeezed into a desktop shell."],
        ["Calm UI", "The interface supports understanding and action without noisy badges or false urgency."],
      ],
      chapters: [
        { id: "energyflow", num: "01 / EnergyFlow", title: "See what your workday does to your energy.", body: "Log energy in seconds, then review how meetings, deep work, breaks, and overtime shape your state over time.", bullets: ["5-level energy state", "Work context", "Pearson + Chi-square", "Local privacy"] },
        { id: "deskhaven", num: "02 / DeskHaven", title: "Give local files a system you can trust.", body: "DeskHaven turns loose files into a searchable, archivable workspace with relationship maps, backup, and privacy controls.", bullets: ["File vault", "Relationship map", "Backup", "AES-256"] },
        { id: "adhd", num: "03 / ADHD Focus Timer", title: "Start focus with less pressure.", body: "Preparation, breathing, forward timing, and Idea Fridge help you begin and return without treating distraction as failure.", bullets: ["Forward timer", "Breathing guide", "Idea Fridge", "Local privacy"] },
      ],
      principlesTitle: "Less interruption. More control.",
      principlesBody: "SoloCraft products do not chase feature bloat. Each one finishes a specific job: understanding energy patterns, easing into focus, or turning scattered files into a system you can trust.",
      productTitle: "Choose a tool for the workflow in front of you.",
      studioTitle: "Small tools made for repeated use.",
      studioBody: "I care more about whether a product fits quietly into daily work than whether it feels loud on first launch. Real screenshots, clear privacy notes, and verifiable behavior matter more than decoration.",
      studioNote: "EnergyFlow, DeskHaven, and ADHD Focus Timer cover energy tracking, file organization, and low-resistance focus. Each product page shows features, screenshots, privacy notes, and download options directly.",
    },
    products: {
      eyebrow: "Product index",
      title: "Choose the desktop tool you need right now.",
      intro: "Each product page shows real interface screenshots, core features, privacy details, and download links, so you can understand the problem it solves before installing.",
    },
    productCards: {
      energyflow: { title: "EnergyFlow", category: "Workplace energy dashboard", description: "Log energy in seconds, then use trends and statistics to see which meetings, tasks, and routines actually drain or restore you.", status: "Available" },
      deskhaven: { title: "DeskHaven", category: "Desktop file haven", description: "Give scattered local files a private workbench with vaults, search, relationship maps, backup, and privacy controls.", status: "Available" },
      adhd: { title: "ADHD Focus Timer", category: "Low-pressure focus timer", description: "Use preparation, breathing, forward timing, and Idea Fridge to start and sustain focus with less resistance.", status: "Available" },
    },
    energyflow: {
      eyebrow: "EnergyFlow / Workplace Energy Dashboard",
      title: "Track energy changes and see what work really costs.",
      intro: "EnergyFlow turns a quick check-in into useful history: energy level, work state, recovery source, and mood. Over time, trends and statistics help reveal which meetings, tasks, and routines affect your energy.",
      status: "Available",
      promiseTitle: "Not a to-do list. A record of your working energy.",
      promise: "EnergyFlow does not judge whether you worked hard enough. It helps turn daily feelings into a timeline you can review, so patterns around recovery, drain, and schedule choices become easier to see.",
      features: [
        ["Three-second logging", "Record energy level, work status, energy source, and mood with minimal friction."],
        ["Dark or light clarity", "Deep mode for focus and light mode for daytime work, without loud interface noise."],
        ["Always on desktop", "A floating entry and hotkey make logging appear, record, and disappear without breaking flow."],
        ["Statistical insight", "Pearson correlation and Chi-square analysis help reveal which contexts really affect energy."],
        ["Privacy protection", "Energy state data is sensitive. EnergyFlow is designed with local-first privacy as the default."],
      ],
      flow: ["Capture state", "Accumulate context", "Review energy patterns", "Adjust work rhythm"],
    },
    deskhaven: {
      eyebrow: "DeskHaven / Desktop File Haven",
      title: "Turn scattered files into a local workspace you can trust.",
      intro: "DeskHaven organizes local Windows files into a searchable, archivable, recoverable workspace for documents, images, exports, and project materials, with relationship maps to help you understand how content connects.",
      status: "Available",
      promiseTitle: "Not another folder. A local system for file order.",
      promise: "The vault gathers and archives, search brings files back quickly, relationship maps make context visible, and backup plus privacy controls keep important data recoverable, exportable, and under your control.",
      features: [
        ["Overview before detail", "The dashboard summarizes file count, relationships, encryption state, and storage trends so users know whether their desktop is under control."],
        ["File vault", "The vault manages local files, metadata, and archive state. It is a quiet local layer, not another cloud drive."],
        ["Relationship map", "Files, tags, topics, and projects can be seen as relationships. Users do not only find files; they understand why files matter."],
        ["Privacy and control", "Keys, import, export, encryption, and control options live in one clear place. Important data should remain under user control."],
        ["Automation that stays quiet", "Background automation, paths, switches, and language settings are grouped clearly, so cleanup does not become another daily system."],
      ],
      principles: [
        ["Local-first", "Important files and indexes are handled locally by default."],
        ["Controlled", "Users should know where files are and how to recover them."],
        ["Relational", "Projects, tags, and content connections should be understandable."],
        ["Low-friction", "Organization should happen naturally without becoming a new burden."],
      ],
    },
    adhd: {
      eyebrow: "ADHD Focus Timer / Low-pressure focus",
      title: "Start focused work with less pressure.",
      intro: "ADHD Focus Timer uses a preparation screen, breathing transition, forward timer, and Idea Fridge to reduce the resistance of starting. It treats distraction as something to handle, not a personal failure.",
      status: "Available",
      promiseTitle: "A focus timer should reduce pressure, not add it.",
      promise: "Forward timing avoids the failure feeling of a countdown, Idea Fridge gives stray thoughts a temporary place, and the completion screen records real effort without grading you.",
      features: [
        ["Lower the noise first", "The intro and preparation screens explain what will happen next, reducing resistance before a task begins."],
        ["Prepare, do not pressure", "Duration, white noise, language, and breathing are selected before focus starts to reduce mid-session choices."],
        ["Breathing transition", "A short breathing guide helps shift from scattered attention into a focused state."],
        ["Forward timing", "Time accumulates forward instead of counting down toward failure. Particles and progress provide quiet companionship."],
        ["Idea Fridge", "Unexpected thoughts can be parked without being obeyed immediately, then revisited after the session."],
        ["Gentle completion", "Ending a session is not a judgment. The achievement screen records a real completion with soft feedback."],
        ["Support and privacy", "Local-first behavior, minimal data, and clear privacy language keep focus data from becoming another source of pressure."],
      ],
    },
    about: {
      title: "About SoloCraft",
      intro: "SoloCraft is Chicken Fillet's independent desktop software studio for quiet, restrained, privacy-first tools.",
      story: [
        "I like tools that do not steal the stage. They should appear when needed and return to the background when the work is done.",
        "EnergyFlow, DeskHaven, and ADHD Focus Timer all circle the same question: how can desktop work become more recoverable, understandable, and less stressful?",
        "This site shows the products as they are: real screens, use cases, privacy notes, and download paths, without loud packaging standing in for the software.",
      ],
      philosophyTitle: "Design principles",
      philosophy: [
        ["Small and complete", "Each tool focuses on a clear scenario while completing the important workflow."],
        ["Desktop-native", "Built around actual desktop workflows, not another web dashboard in disguise."],
        ["Restrained", "Visual design serves understanding instead of manufacturing cheap excitement."],
        ["Privacy-first", "Data that can stay local should not leave the device lightly."],
      ],
      techTitle: "Technical direction",
      tech: ["Windows desktop apps", "Local-first storage", "Statistics and visualization", "Privacy-conscious product design"],
      ctaTitle: "Want to talk products, collaboration, or feedback?",
      ctaDescription: "I read every real note carefully.",
      ctaButton: "Contact me",
    },
    contact: {
      title: "Contact",
      intro: "Product feedback, collaboration ideas, media questions, or a simple hello can all go to email.",
      infoTitle: "Contact information",
      email: "Email",
    },
    footer: {
      subtitle: "Independent desktop software by Chicken Fillet.",
      studio: "Studio",
      products: "Products",
      legal: "Legal",
      about: "About",
      contact: "Contact",
      privacy: "Privacy Policy",
      copyright: "Quiet, restrained, privacy-first desktop tools.",
    },
  },
};

const localized: Partial<Record<Locale, typeof siteCopy.en>> = {
  "zh-tw": {
    ...siteCopy.zh,
    common: { ...siteCopy.zh.common, productPromise: "產品承諾", experienceFlow: "體驗流程", productIndex: "產品索引", operatingPrinciples: "工作原則", designPrinciples: "設計原則", step: "步驟", viewProducts: "查看產品", contact: "聯絡", getUpdates: "聯絡開發者", microsoftStore: "Microsoft Store", privacy: "隱私政策", backToProducts: "返回產品" },
    products: { eyebrow: "產品索引", title: "選擇你現在需要的桌面工具。", intro: "每個產品頁都展示真實界面、核心功能、隱私說明和下載入口。先看清它解決什麼問題，再決定是否安裝。" },
    about: { ...siteCopy.zh.about, title: "關於 SoloCraft", ctaButton: "聯絡我" },
    contact: { title: "聯絡", intro: "產品回饋、合作想法、媒體詢問，或只是打個招呼，都可以用郵件聯絡我。", infoTitle: "聯絡方式", email: "郵箱" },
    footer: { ...siteCopy.zh.footer, studio: "工作室", products: "產品", legal: "法務", about: "關於", contact: "聯絡", privacy: "隱私政策" },
  },
  ru: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "Обещание продукта", experienceFlow: "Сценарий работы", productIndex: "Каталог продуктов", operatingPrinciples: "Принципы", designPrinciples: "Принципы дизайна", step: "Шаг", viewProducts: "Смотреть продукты", contact: "Контакты", getUpdates: "Связаться с разработчиком", microsoftStore: "Microsoft Store", privacy: "Политика конфиденциальности", backToProducts: "Назад к продуктам" },
    home: { ...siteCopy.en.home, eyebrow: "Независимое ПО для Windows", title: "Больше контроля над энергией, фокусом и локальными файлами.", intro: "SoloCraft объединяет инструменты Chicken Fillet для рабочей энергии, мягкого фокуса и порядка в локальных файлах.", primary: "Посмотреть подход", secondary: "Смотреть продукты", currentProduct: "Сейчас показано", productTitle: "Выберите инструмент под текущую задачу.", studioTitle: "Небольшие инструменты для ежедневной работы." },
    products: { eyebrow: "Каталог продуктов", title: "Выберите настольный инструмент, который нужен сейчас.", intro: "На страницах продуктов показаны реальные экраны, ключевые функции, детали приватности и ссылки на загрузку, чтобы решение было понятным до установки." },
    about: { ...siteCopy.en.about, title: "О SoloCraft", intro: "SoloCraft — независимая студия Chicken Fillet для спокойных, сдержанных и privacy-first настольных инструментов.", ctaButton: "Связаться" },
    contact: { title: "Контакты", intro: "Отзывы о продукте, идеи сотрудничества, запросы медиа или короткое приветствие можно отправить по почте.", infoTitle: "Контакт", email: "Почта" },
    footer: { ...siteCopy.en.footer, studio: "Студия", products: "Продукты", legal: "Правовое", about: "О нас", contact: "Контакты", privacy: "Конфиденциальность" },
  },
  pt: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "Promessa do produto", experienceFlow: "Fluxo de experiência", productIndex: "Índice de produtos", operatingPrinciples: "Princípios", designPrinciples: "Princípios de design", step: "Etapa", viewProducts: "Ver produtos", contact: "Contato", getUpdates: "Falar com o desenvolvedor", microsoftStore: "Microsoft Store", privacy: "Política de privacidade", backToProducts: "Voltar aos produtos" },
    home: { ...siteCopy.en.home, eyebrow: "Software independente para Windows", title: "Mais controle sobre energia, foco e arquivos locais.", intro: "SoloCraft reúne ferramentas da Chicken Fillet para acompanhar energia de trabalho, reduzir atrito no foco e organizar arquivos locais.", primary: "Ver a abordagem", secondary: "Ver produtos", currentProduct: "Em destaque", productTitle: "Escolha uma ferramenta para o fluxo de trabalho de agora.", studioTitle: "Ferramentas pequenas para uso diário." },
    products: { eyebrow: "Índice de produtos", title: "Escolha a ferramenta desktop que você precisa agora.", intro: "Cada página mostra telas reais, recursos principais, detalhes de privacidade e links de download para você entender antes de instalar." },
    about: { ...siteCopy.en.about, title: "Sobre o SoloCraft", intro: "SoloCraft é o estúdio independente da Chicken Fillet para ferramentas desktop calmas, discretas e privacy-first.", ctaButton: "Entrar em contato" },
    contact: { title: "Contato", intro: "Feedback de produto, ideias de colaboração, pedidos de mídia ou um simples oi podem chegar por e-mail.", infoTitle: "Contato", email: "E-mail" },
    footer: { ...siteCopy.en.footer, studio: "Estúdio", products: "Produtos", legal: "Legal", about: "Sobre", contact: "Contato", privacy: "Privacidade" },
  },
  ja: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "製品の約束", experienceFlow: "体験の流れ", productIndex: "製品一覧", operatingPrinciples: "運用原則", designPrinciples: "設計原則", step: "ステップ", viewProducts: "製品を見る", contact: "連絡", getUpdates: "開発者に連絡", privacy: "プライバシーポリシー", backToProducts: "製品に戻る" },
    home: { ...siteCopy.en.home, eyebrow: "独立系デスクトップソフトウェアスタジオ", title: "集中するデスクトップ作業のための静かなツール。", intro: "SoloCraft は Chicken Fillet の製品ホームです。エネルギーを記録し、集中を守り、デスクトップを落ち着かせる小さく控えめな Windows ツールを作っています。" },
    products: { eyebrow: "製品一覧", title: "今必要なデスクトップツールを選ぶ。", intro: "各製品ページでは実際の画面、主な機能、プライバシー情報、ダウンロード導線を確認できます。インストール前に用途を把握できます。" },
    about: { ...siteCopy.en.about, title: "SoloCraft について", intro: "SoloCraft は Chicken Fillet の独立系デスクトップソフトウェアスタジオです。静かで控えめ、プライバシーを重視したツールを作ります。" },
    contact: { title: "連絡", intro: "製品フィードバック、協業の相談、メディア問い合わせ、または短い挨拶でもメールでどうぞ。", infoTitle: "連絡先", email: "メール" },
    footer: { ...siteCopy.en.footer, studio: "スタジオ", products: "製品", legal: "法務", about: "概要", contact: "連絡", privacy: "プライバシーポリシー" },
  },
  ko: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "제품 약속", experienceFlow: "경험 흐름", productIndex: "제품 목록", operatingPrinciples: "운영 원칙", designPrinciples: "설계 원칙", step: "단계", viewProducts: "제품 보기", contact: "연락", getUpdates: "개발자에게 문의", privacy: "개인정보 처리방침", backToProducts: "제품으로 돌아가기" },
    home: { ...siteCopy.en.home, eyebrow: "독립 데스크톱 소프트웨어 스튜디오", title: "집중하는 데스크톱 작업을 위한 조용한 도구.", intro: "SoloCraft는 Chicken Fillet의 제품 홈입니다. 에너지를 기록하고, 집중을 보호하고, 데스크톱을 차분하게 만드는 작고 절제된 Windows 도구를 만듭니다." },
    products: { eyebrow: "제품 목록", title: "지금 필요한 데스크톱 도구를 선택하세요.", intro: "각 제품 페이지에서 실제 화면, 핵심 기능, 개인정보 설명과 다운로드 링크를 확인한 뒤 설치 여부를 결정할 수 있습니다." },
    about: { ...siteCopy.en.about, title: "SoloCraft 소개", intro: "SoloCraft는 Chicken Fillet의 독립 데스크톱 소프트웨어 스튜디오로, 조용하고 절제되며 개인정보를 우선하는 도구를 만듭니다." },
    contact: { title: "연락", intro: "제품 피드백, 협업 아이디어, 미디어 문의 또는 짧은 인사도 이메일로 보내 주세요.", infoTitle: "연락처", email: "이메일" },
    footer: { ...siteCopy.en.footer, studio: "스튜디오", products: "제품", legal: "법무", about: "소개", contact: "연락", privacy: "개인정보 처리방침" },
  },
  fr: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "Promesse produit", experienceFlow: "Parcours", productIndex: "Index des produits", operatingPrinciples: "Principes", designPrinciples: "Principes de design", step: "Étape", viewProducts: "Voir les produits", contact: "Contact", getUpdates: "Contacter le développeur", privacy: "Confidentialité", backToProducts: "Retour aux produits" },
    home: { ...siteCopy.en.home, eyebrow: "Studio indépendant de logiciels desktop", title: "Des outils calmes pour le travail concentré.", intro: "SoloCraft est la maison produit de Chicken Fillet : de petits outils Windows sobres pour suivre l'énergie, protéger la concentration et apaiser le bureau." },
    products: { eyebrow: "Index des produits", title: "Choisissez l'outil desktop dont vous avez besoin.", intro: "Chaque page produit montre les écrans réels, les fonctions clés, les détails de confidentialité et les liens de téléchargement avant installation." },
    about: { ...siteCopy.en.about, title: "À propos de SoloCraft", intro: "SoloCraft est le studio indépendant de Chicken Fillet pour des outils desktop calmes, sobres et respectueux de la vie privée." },
    contact: { title: "Contact", intro: "Retours produit, idées de collaboration, demandes presse ou simple bonjour peuvent arriver par e-mail.", infoTitle: "Coordonnées", email: "E-mail" },
    footer: { ...siteCopy.en.footer, studio: "Studio", products: "Produits", legal: "Mentions", about: "À propos", contact: "Contact", privacy: "Confidentialité" },
  },
  de: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "Produktversprechen", experienceFlow: "Ablauf", productIndex: "Produktübersicht", operatingPrinciples: "Arbeitsprinzipien", designPrinciples: "Designprinzipien", step: "Schritt", viewProducts: "Produkte ansehen", contact: "Kontakt", getUpdates: "Entwickler kontaktieren", privacy: "Datenschutz", backToProducts: "Zurück zu Produkten" },
    home: { ...siteCopy.en.home, eyebrow: "Unabhängiges Desktop-Softwarestudio", title: "Ruhige Werkzeuge für fokussierte Desktop-Arbeit.", intro: "SoloCraft ist die Produktseite von Chicken Fillet: kleine, zurückhaltende Windows-Tools zum Erfassen von Energie, Schützen von Fokus und Beruhigen des Desktops." },
    products: { eyebrow: "Produktübersicht", title: "Wähle das Desktop-Tool, das du gerade brauchst.", intro: "Jede Produktseite zeigt echte Oberflächen, Kernfunktionen, Datenschutzdetails und Downloadlinks, bevor du installierst." },
    about: { ...siteCopy.en.about, title: "Über SoloCraft", intro: "SoloCraft ist Chicken Fillets unabhängiges Studio für ruhige, zurückhaltende und datenschutzbewusste Desktop-Tools." },
    contact: { title: "Kontakt", intro: "Produktfeedback, Kooperationsideen, Medienanfragen oder ein kurzes Hallo können per E-Mail kommen.", infoTitle: "Kontaktinformationen", email: "E-Mail" },
    footer: { ...siteCopy.en.footer, studio: "Studio", products: "Produkte", legal: "Rechtliches", about: "Über uns", contact: "Kontakt", privacy: "Datenschutz" },
  },
  es: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "Promesa del producto", experienceFlow: "Flujo de experiencia", productIndex: "Índice de productos", operatingPrinciples: "Principios", designPrinciples: "Principios de diseño", step: "Paso", viewProducts: "Ver productos", contact: "Contacto", getUpdates: "Contactar al desarrollador", privacy: "Privacidad", backToProducts: "Volver a productos" },
    home: { ...siteCopy.en.home, eyebrow: "Estudio independiente de software de escritorio", title: "Herramientas tranquilas para trabajar con foco.", intro: "SoloCraft es el hogar de productos de Chicken Fillet: pequeñas herramientas de Windows, sobrias, para registrar energía, proteger el foco y mantener el escritorio en calma." },
    products: { eyebrow: "Índice de productos", title: "Elige la herramienta de escritorio que necesitas ahora.", intro: "Cada página muestra pantallas reales, funciones principales, detalles de privacidad y enlaces de descarga antes de instalar." },
    about: { ...siteCopy.en.about, title: "Acerca de SoloCraft", intro: "SoloCraft es el estudio independiente de Chicken Fillet para herramientas de escritorio tranquilas, sobrias y centradas en la privacidad." },
    contact: { title: "Contacto", intro: "Comentarios de producto, ideas de colaboración, consultas de prensa o un simple saludo pueden llegar por correo.", infoTitle: "Información de contacto", email: "Correo" },
    footer: { ...siteCopy.en.footer, studio: "Estudio", products: "Productos", legal: "Legal", about: "Acerca de", contact: "Contacto", privacy: "Privacidad" },
  },
};

const productLocaleCopy: Partial<Record<Locale, Pick<typeof siteCopy.en, "productCards" | "energyflow" | "deskhaven" | "adhd">>> = {
  "zh-tw": {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "職場能量儀表盤", description: "幾秒記錄精力、工作狀態和能量來源，用統計洞察看清消耗與恢復。", status: "已推出" },
      deskhaven: { title: "DeskHaven", category: "桌面文件避風港", description: "給每份文件一個本地、可控、可追溯的工作台，結合檔案櫃、關係圖譜與隱私控制。", status: "已推出" },
      adhd: { title: "ADHD Focus Timer", category: "低壓力專注計時器", description: "正向計時、呼吸過渡、想法冰箱和沉浸式專注環境，讓開始更溫和。", status: "已推出" },
    },
    energyflow: { ...siteCopy.zh.energyflow, status: "已推出" },
    deskhaven: { ...siteCopy.zh.deskhaven, title: "守護你的每一份文件。", status: "已推出" },
    adhd: { ...siteCopy.zh.adhd, status: "已推出" },
  },
  ru: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "Панель рабочей энергии", description: "Записывайте энергию за секунды и находите, что истощает или восстанавливает вас.", status: "Доступно" },
      deskhaven: { title: "DeskHaven", category: "Убежище для файлов", description: "Локальная рабочая зона для файлов: архив, карта связей, приватность и автоматизация.", status: "Доступно" },
      adhd: { title: "ADHD Focus Timer", category: "Мягкий таймер фокуса", description: "Прямой таймер, дыхательный переход, Idea Fridge и спокойный полноэкранный фокус.", status: "Доступно" },
    },
    energyflow: { ...siteCopy.en.energyflow, eyebrow: "EnergyFlow / Панель рабочей энергии", title: "Поймите, куда уходит энергия рабочего дня.", intro: "Записывайте уровень энергии, контекст, источник и настроение за несколько секунд.", status: "Доступно" },
    deskhaven: { ...siteCopy.en.deskhaven, eyebrow: "DeskHaven / Убежище для файлов", title: "Личный рабочий стол для каждого файла.", intro: "DeskHaven организует локальные Windows-файлы через архив, карту связей, контроль приватности и тихую автоматизацию.", status: "Доступно" },
    adhd: { ...siteCopy.en.adhd, eyebrow: "ADHD Focus Timer / Мягкий фокус", title: "Фокус без наказания внимания.", intro: "Инструмент с дыхательным переходом, прямым таймером, Idea Fridge и local-first приватностью.", status: "Доступно" },
  },
  pt: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "Painel de energia no trabalho", description: "Registre energia em segundos e entenda o que drena ou restaura você.", status: "Disponível" },
      deskhaven: { title: "DeskHaven", category: "Refúgio de arquivos desktop", description: "Uma mesa local para cada arquivo, com arquivo, mapa de relações, privacidade e automação.", status: "Disponível" },
      adhd: { title: "ADHD Focus Timer", category: "Timer de foco suave", description: "Contagem progressiva, respiração, Idea Fridge e foco em tela cheia com baixa resistência.", status: "Disponível" },
    },
    energyflow: { ...siteCopy.en.energyflow, eyebrow: "EnergyFlow / Painel de energia", title: "Entenda para onde vai sua energia de trabalho.", intro: "Registre nível de energia, contexto, fonte e humor em poucos segundos.", status: "Disponível" },
    deskhaven: { ...siteCopy.en.deskhaven, eyebrow: "DeskHaven / Refúgio de arquivos", title: "Uma mesa privada para cada arquivo.", intro: "DeskHaven organiza arquivos locais do Windows com arquivo, mapa de relações, privacidade e automação tranquila.", status: "Disponível" },
    adhd: { ...siteCopy.en.adhd, eyebrow: "ADHD Focus Timer / Foco suave", title: "Foco sem transformar atenção em julgamento.", intro: "Ferramenta com transição respiratória, contagem progressiva, Idea Fridge e privacidade local-first.", status: "Disponível" },
  },
  ja: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "仕事のエネルギーダッシュボード", description: "数秒でエネルギーを記録し、仕事の状態や回復源を統計的に見える化します。", status: "公開中" },
      deskhaven: { title: "DeskHaven", category: "デスクトップファイルの避難所", description: "ローカルの保管庫、関係マップ、プライバシー制御で、散らばったファイルに静かな作業台を作ります。", status: "公開中" },
      adhd: { title: "ADHD Focus Timer", category: "低圧の集中タイマー", description: "前向きな計時、呼吸の移行、Idea Fridge、落ち着いた全画面集中環境。", status: "公開中" },
    },
    energyflow: {
      ...siteCopy.en.energyflow,
      eyebrow: "EnergyFlow / 仕事のエネルギーダッシュボード",
      title: "仕事日のエネルギーがどこへ流れるかを見る。",
      intro: "5 段階のエネルギー、仕事の文脈、回復源、気分を数秒で記録します。EnergyFlow は、消耗する会議や回復するタスクを見つけるための道具です。",
      status: "公開中",
      promiseTitle: "タスクアプリではなく、エネルギーリズムの計器盤。",
      promise: "もっと働かせるためではなく、会議、残業、深い作業、休憩が集中力に与える本当のコストを見るための製品です。",
      features: [
        ["3 秒ログ", "エネルギー、状態、回復源、気分を少ない操作で記録します。"],
        ["明暗モード", "集中用のダークモードと日中作業用のライトモード。"],
        ["デスクトップ常駐", "フローティング入口とショートカットで流れを止めずに記録します。"],
        ["統計洞察", "相関とカイ二乗検定で、文脈とエネルギーの関係を観察します。"],
        ["プライバシー保護", "エネルギーデータは個人的です。ローカル優先を基本に設計しています。"],
      ],
      flow: ["状態を記録", "文脈を蓄積", "傾向を確認", "働き方を調整"],
    },
    deskhaven: {
      ...siteCopy.en.deskhaven,
      eyebrow: "DeskHaven / デスクトップファイルの避難所",
      title: "すべてのファイルに私的な作業台を。",
      intro: "DeskHaven はローカル優先の Windows デスクトップ整理ツールです。保管庫、関係マップ、プライバシー制御、自動化で、散らばったファイルを落ち着いた状態に戻します。",
      status: "公開中",
      promiseTitle: "うるさいファイル管理ではなく、内容のための静かな場所。",
      promise: "ファイルを隠すのではなく、関係を理解しやすくします。保管庫、関係マップ、プライバシー制御、設定がそれぞれ役割を持ちます。",
      features: [
        ["まず全体を見る", "ダッシュボードでファイル数、関係、暗号化状態、保存傾向を確認します。"],
        ["ファイル保管庫", "ローカルファイル、メタデータ、アーカイブ状態を静かに管理します。"],
        ["関係マップ", "ファイル、タグ、テーマ、プロジェクトのつながりを見える化します。"],
        ["プライバシーと制御", "鍵、インポート、エクスポート、暗号化を分かりやすく配置します。"],
        ["静かな自動化", "整理は背景で自然に行われ、毎日の負担になりません。"],
      ],
      principles: [
        ["ローカル優先", "重要なファイルと索引は基本的に端末内で処理します。"],
        ["制御可能", "ファイルの場所と復元方法を利用者が把握できます。"],
        ["関係を見る", "タグやプロジェクトとのつながりを理解できます。"],
        ["低摩擦", "整理が新しい負担にならないようにします。"],
      ],
    },
    adhd: {
      ...siteCopy.en.adhd,
      eyebrow: "ADHD Focus Timer / 低圧の集中",
      title: "注意力を裁かず、やさしく集中へ入る。",
      intro: "呼吸の移行、前向きな計時、粒子の伴走、Idea Fridge、ローカル優先のプライバシーを備えた集中ツールです。",
      status: "公開中",
      promiseTitle: "集中はカウントダウンの罰であるべきではありません。",
      promise: "タイマーは圧力になりがちです。この製品は開始、継続、分心の受け止めをやさしく支えます。",
      features: [
        ["先にノイズを下げる", "開始前に流れを説明し、心理的抵抗を減らします。"],
        ["準備する", "時間、音、言語、呼吸を先に選びます。"],
        ["呼吸の移行", "短い呼吸ガイドで状態を切り替えます。"],
        ["前向きな計時", "時間を積み上げ、失敗感を避けます。"],
        ["Idea Fridge", "浮かんだ考えを一時的に置いておけます。"],
        ["やさしい完了", "終了は評価ではなく、実際の完了記録です。"],
        ["支援とプライバシー", "最小データとローカル優先で、集中データを負担にしません。"],
      ],
    },
  },
  ko: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "업무 에너지 대시보드", description: "몇 초 만에 에너지를 기록하고 업무 상태와 회복 요인을 통계로 이해합니다.", status: "출시됨" },
      deskhaven: { title: "DeskHaven", category: "데스크톱 파일 안식처", description: "로컬 보관함, 관계 지도, 개인정보 제어로 흩어진 파일에 조용한 작업대를 만듭니다.", status: "출시됨" },
      adhd: { title: "ADHD Focus Timer", category: "저압 집중 타이머", description: "정방향 타이머, 호흡 전환, Idea Fridge, 차분한 전체 화면 집중 환경.", status: "출시됨" },
    },
    energyflow: { ...siteCopy.en.energyflow, eyebrow: "EnergyFlow / 업무 에너지 대시보드", title: "업무 에너지가 어디로 흐르는지 이해하세요.", intro: "5단계 에너지, 업무 맥락, 회복 요인, 기분을 몇 초 안에 기록합니다.", status: "출시됨", promiseTitle: "또 하나의 할 일 앱이 아니라 에너지 리듬 대시보드.", promise: "더 열심히 일하게 만드는 도구가 아니라 회의, 야근, 깊은 작업, 휴식이 에너지에 미치는 비용을 보여줍니다.", features: [["3초 기록", "최소한의 마찰로 에너지와 맥락을 남깁니다."], ["명암 모드", "집중과 낮 시간 업무에 맞는 차분한 화면."], ["데스크톱 상주", "떠 있는 진입점과 단축키로 흐름을 끊지 않습니다."], ["통계 인사이트", "상관과 카이제곱으로 맥락의 영향을 봅니다."], ["개인정보 보호", "에너지 데이터는 민감하므로 로컬 우선을 기본으로 합니다."]], flow: ["상태 기록", "맥락 축적", "패턴 확인", "리듬 조정"] },
    deskhaven: { ...siteCopy.en.deskhaven, eyebrow: "DeskHaven / 데스크톱 파일 안식처", title: "모든 파일을 위한 개인 작업대.", intro: "DeskHaven은 로컬 우선 Windows 데스크톱 정리 도구입니다. 보관함, 관계 지도, 개인정보 제어, 자동화로 파일을 차분하게 정리합니다.", status: "출시됨", promiseTitle: "시끄러운 파일 관리자가 아닌 조용한 콘텐츠 작업공간.", promise: "파일을 숨기는 것이 아니라 관계를 이해하게 돕습니다.", features: [["전체를 먼저 보기", "대시보드가 파일 수, 관계, 암호화 상태, 저장 추세를 요약합니다."], ["파일 보관함", "로컬 파일과 메타데이터를 조용히 관리합니다."], ["관계 지도", "파일, 태그, 주제, 프로젝트의 연결을 봅니다."], ["개인정보와 제어", "키, 가져오기, 내보내기, 암호화를 명확히 둡니다."], ["조용한 자동화", "정리가 매일의 새 부담이 되지 않게 합니다."]], principles: [["로컬 우선", "중요한 파일과 색인은 기본적으로 로컬에서 처리합니다."], ["제어 가능", "파일 위치와 복구 방법을 알 수 있습니다."], ["관계 중심", "프로젝트와 태그의 연결을 이해합니다."], ["낮은 마찰", "정리가 자연스럽게 일어납니다."]] },
    adhd: { ...siteCopy.en.adhd, eyebrow: "ADHD Focus Timer / 저압 집중", title: "주의력을 벌하지 않고 부드럽게 상태에 들어가기.", intro: "호흡 전환, 정방향 타이머, 입자 동반, Idea Fridge, 로컬 우선 개인정보를 갖춘 집중 도구입니다.", status: "출시됨", promiseTitle: "집중은 카운트다운 처벌처럼 느껴져서는 안 됩니다.", promise: "이 도구는 시작, 지속, 산만함을 받아 주는 데 초점을 둡니다.", features: [["먼저 소음 낮추기", "시작 전 흐름을 알려 저항을 줄입니다."], ["준비하기", "시간, 소리, 언어, 호흡을 먼저 정합니다."], ["호흡 전환", "짧은 호흡 가이드로 상태를 바꿉니다."], ["정방향 타이머", "시간을 쌓아 실패감을 줄입니다."], ["Idea Fridge", "떠오른 생각을 잠시 보관합니다."], ["부드러운 완료", "끝은 평가가 아니라 실제 완료 기록입니다."], ["지원과 개인정보", "최소 데이터와 로컬 우선으로 부담을 줄입니다."]] },
  },
  fr: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "Tableau d'énergie au travail", description: "Notez votre énergie en quelques secondes et comprenez ce qui vous épuise ou vous restaure.", status: "Disponible" },
      deskhaven: { title: "DeskHaven", category: "Havre de fichiers desktop", description: "Un bureau privé pour chaque fichier, avec coffres locaux, cartes de relations et contrôles de confidentialité.", status: "Disponible" },
      adhd: { title: "ADHD Focus Timer", category: "Minuteur de concentration doux", description: "Chronométrage progressif, respiration, Idea Fridge et environnement plein écran apaisé.", status: "Disponible" },
    },
    energyflow: { ...siteCopy.en.energyflow, eyebrow: "EnergyFlow / Tableau d'énergie au travail", title: "Comprendre où va votre énergie de travail.", intro: "Enregistrez en quelques secondes votre niveau d'énergie, le contexte, la source et l'humeur.", status: "Disponible", promiseTitle: "Pas une autre app de tâches, mais un tableau pour votre rythme.", promise: "EnergyFlow aide à voir le coût réel des réunions, heures longues, travail profond et pauses.", features: [["Journal en trois secondes", "Enregistrez énergie, état, source et humeur avec peu de friction."], ["Clarté sombre ou claire", "Modes sobres pour concentration ou travail de jour."], ["Présent sur le bureau", "Entrée flottante et raccourci sans casser le flux."], ["Analyse statistique", "Corrélations et khi carré révèlent les contextes qui comptent."], ["Confidentialité", "Les données d'énergie restent pensées localement par défaut."]], flow: ["Capturer l'état", "Accumuler le contexte", "Lire les tendances", "Ajuster le rythme"] },
    deskhaven: { ...siteCopy.en.deskhaven, eyebrow: "DeskHaven / Havre de fichiers desktop", title: "Un bureau privé pour chaque fichier.", intro: "DeskHaven est un outil Windows local-first pour organiser les fichiers avec coffres, relations, confidentialité et automatisation.", status: "Disponible", promiseTitle: "Un espace calme pour le contenu, pas un gestionnaire bruyant.", promise: "DeskHaven ne cache pas les fichiers : il rend leurs liens plus compréhensibles.", features: [["Vue d'ensemble", "Le tableau résume fichiers, relations, chiffrement et stockage."], ["Coffre de fichiers", "Une couche locale calme pour fichiers et métadonnées."], ["Carte de relations", "Voir les liens entre fichiers, tags, sujets et projets."], ["Confidentialité et contrôle", "Clés, import, export et chiffrement restent lisibles."], ["Automatisation discrète", "Le rangement se fait en arrière-plan sans nouvelle charge."]], principles: [["Local-first", "Les fichiers importants sont traités localement par défaut."], ["Contrôlé", "L'utilisateur sait où sont les fichiers et comment les récupérer."], ["Relationnel", "Les liens entre projets, tags et contenus restent visibles."], ["Faible friction", "L'organisation ne devient pas une nouvelle charge."]] },
    adhd: { ...siteCopy.en.adhd, eyebrow: "ADHD Focus Timer / Concentration douce", title: "Se concentrer sans transformer l'attention en procès.", intro: "Un outil immersif avec respiration, chronométrage progressif, particules, Idea Fridge et confidentialité locale.", status: "Disponible", promiseTitle: "La concentration ne devrait pas ressembler à une punition.", promise: "Le produit aide à entrer, rester et accueillir les distractions sans culpabiliser.", features: [["Réduire le bruit", "Les écrans d'introduction diminuent la résistance au démarrage."], ["Préparer", "Durée, son, langue et respiration sont choisis avant la session."], ["Transition respiratoire", "Un court guide aide à changer d'état."], ["Chronométrage progressif", "Le temps s'accumule au lieu de compter vers l'échec."], ["Idea Fridge", "Les idées soudaines peuvent attendre."], ["Fin douce", "La fin enregistre une vraie complétion sans jugement."], ["Soutien et vie privée", "Peu de données, local-first, langage clair."]] },
  },
  de: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "Energie-Dashboard für Arbeit", description: "Erfasse Energie in Sekunden und verstehe, was dich erschöpft oder wieder auflädt.", status: "Verfügbar" },
      deskhaven: { title: "DeskHaven", category: "Desktop-Dateihafen", description: "Ein privater Schreibtisch für jede Datei, mit lokalen Tresoren, Beziehungskarten und Datenschutzkontrolle.", status: "Verfügbar" },
      adhd: { title: "ADHD Focus Timer", category: "Sanfter Fokus-Timer", description: "Vorwärtszählung, Atemübergang, Idea Fridge und ruhige Vollbildumgebung.", status: "Verfügbar" },
    },
    energyflow: { ...siteCopy.en.energyflow, eyebrow: "EnergyFlow / Energie-Dashboard", title: "Verstehe, wohin deine Arbeitsenergie geht.", intro: "Erfasse Energie, Kontext, Quelle und Stimmung in wenigen Sekunden.", status: "Verfügbar", promiseTitle: "Keine weitere Aufgaben-App, sondern ein Dashboard für deinen Rhythmus.", promise: "EnergyFlow zeigt die echten Kosten von Meetings, Überstunden, Tiefenarbeit und Pausen.", features: [["Drei-Sekunden-Log", "Energie und Kontext mit wenig Reibung erfassen."], ["Hell oder dunkel", "Ruhige Modi für Fokus und Tagesarbeit."], ["Auf dem Desktop", "Schwebender Einstieg und Hotkey ohne Unterbrechung."], ["Statistische Einsicht", "Korrelation und Chi-Quadrat zeigen relevante Kontexte."], ["Datenschutz", "Energiedaten sind sensibel und lokal gedacht."]], flow: ["Zustand erfassen", "Kontext sammeln", "Muster prüfen", "Rhythmus anpassen"] },
    deskhaven: { ...siteCopy.en.deskhaven, eyebrow: "DeskHaven / Desktop-Dateihafen", title: "Ein privater Schreibtisch für jede Datei.", intro: "DeskHaven organisiert lokale Windows-Dateien mit Tresoren, Beziehungskarten, Datenschutz und Automatisierung.", status: "Verfügbar", promiseTitle: "Ein ruhiger Arbeitsraum für Inhalte.", promise: "DeskHaven versteckt Dateien nicht, sondern macht Beziehungen verständlich.", features: [["Überblick zuerst", "Dashboard für Dateien, Beziehungen, Verschlüsselung und Speicher."], ["Dateitresor", "Lokale Dateien und Metadaten ruhig verwalten."], ["Beziehungskarte", "Verbindungen zwischen Dateien, Tags und Projekten sehen."], ["Datenschutz und Kontrolle", "Schlüssel, Import, Export und Verschlüsselung bleiben klar."], ["Leise Automatisierung", "Ordnung passiert im Hintergrund."]], principles: [["Local-first", "Wichtige Dateien bleiben standardmäßig lokal."], ["Kontrolliert", "Dateien und Wiederherstellung bleiben nachvollziehbar."], ["Relational", "Verbindungen bleiben verständlich."], ["Reibungsarm", "Ordnung wird keine neue Last."]] },
    adhd: { ...siteCopy.en.adhd, eyebrow: "ADHD Focus Timer / Sanfter Fokus", title: "Fokus, ohne Aufmerksamkeit zu bestrafen.", intro: "Ein immersives Tool mit Atemübergang, Vorwärtszählung, Partikeln, Idea Fridge und lokaler Privatsphäre.", status: "Verfügbar", promiseTitle: "Fokus sollte sich nicht wie Countdown-Strafe anfühlen.", promise: "Das Produkt unterstützt Einstieg, Fortsetzung und Ablenkungen ohne Schuldgefühl.", features: [["Lärm senken", "Einführung senkt Widerstand vor dem Start."], ["Vorbereiten", "Dauer, Ton, Sprache und Atmung stehen vorher fest."], ["Atemübergang", "Kurze Atemführung wechselt den Zustand."], ["Vorwärtszählung", "Zeit sammelt sich ohne Scheiternsgefühl."], ["Idea Fridge", "Gedanken können geparkt werden."], ["Sanfter Abschluss", "Ende ist Aufzeichnung, kein Urteil."], ["Support und Datenschutz", "Minimale Daten und local-first."]] },
  },
  es: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "Panel de energía laboral", description: "Registra energía en segundos y entiende qué te drena o te restaura.", status: "Disponible" },
      deskhaven: { title: "DeskHaven", category: "Refugio de archivos de escritorio", description: "Un escritorio privado para cada archivo, con bóvedas locales, mapas de relación y privacidad.", status: "Disponible" },
      adhd: { title: "ADHD Focus Timer", category: "Temporizador de foco suave", description: "Conteo hacia adelante, respiración, Idea Fridge y ambiente de foco en pantalla completa.", status: "Disponible" },
    },
    energyflow: { ...siteCopy.en.energyflow, eyebrow: "EnergyFlow / Panel de energía laboral", title: "Entiende a dónde va tu energía de trabajo.", intro: "Registra nivel de energía, contexto, fuente y ánimo en pocos segundos.", status: "Disponible", promiseTitle: "No otra app de tareas, sino un panel para tu ritmo.", promise: "EnergyFlow muestra el costo real de reuniones, horas extra, trabajo profundo y descansos.", features: [["Registro en tres segundos", "Energía y contexto con mínima fricción."], ["Claridad clara u oscura", "Modos sobrios para foco o trabajo diurno."], ["Siempre en el escritorio", "Entrada flotante y atajo sin cortar el flujo."], ["Insight estadístico", "Correlación y chi cuadrado revelan contextos relevantes."], ["Privacidad", "Los datos de energía son sensibles y se diseñan local-first."]], flow: ["Capturar estado", "Acumular contexto", "Revisar patrones", "Ajustar ritmo"] },
    deskhaven: { ...siteCopy.en.deskhaven, eyebrow: "DeskHaven / Refugio de archivos", title: "Un escritorio privado para cada archivo.", intro: "DeskHaven organiza archivos locales de Windows con bóvedas, mapas de relación, privacidad y automatización.", status: "Disponible", promiseTitle: "Un espacio tranquilo para contenido.", promise: "DeskHaven no oculta archivos: ayuda a entender sus relaciones.", features: [["Vista general primero", "Panel de archivos, relaciones, cifrado y almacenamiento."], ["Bóveda de archivos", "Gestiona archivos y metadatos locales con calma."], ["Mapa de relaciones", "Ve conexiones entre archivos, etiquetas y proyectos."], ["Privacidad y control", "Claves, importación, exportación y cifrado claros."], ["Automatización discreta", "El orden sucede en segundo plano."]], principles: [["Local-first", "Los archivos importantes se tratan localmente por defecto."], ["Controlado", "El usuario sabe dónde están y cómo recuperarlos."], ["Relacional", "Las conexiones se entienden."], ["Baja fricción", "Organizar no se vuelve otra carga."]] },
    adhd: { ...siteCopy.en.adhd, eyebrow: "ADHD Focus Timer / Foco suave", title: "Concentrarse sin juzgar la atención.", intro: "Herramienta inmersiva con respiración, conteo hacia adelante, partículas, Idea Fridge y privacidad local.", status: "Disponible", promiseTitle: "El foco no debería sentirse como castigo de cuenta regresiva.", promise: "Ayuda a entrar, sostenerse y recibir distracciones sin culpa.", features: [["Bajar el ruido", "La introducción reduce la resistencia inicial."], ["Preparar", "Duración, sonido, idioma y respiración se eligen antes."], ["Transición respiratoria", "Una guía breve ayuda a cambiar de estado."], ["Conteo hacia adelante", "El tiempo se acumula sin sensación de fracaso."], ["Idea Fridge", "Las ideas repentinas pueden esperar."], ["Cierre suave", "Terminar registra un logro real, no un juicio."], ["Soporte y privacidad", "Datos mínimos y local-first."]] },
  },
};

const launchedStatus: Record<Locale, string> = {
  zh: "已推出",
  "zh-tw": "已推出",
  en: "Available",
  ja: "公開中",
  ko: "출시됨",
  fr: "Disponible",
  de: "Verfügbar",
  es: "Disponible",
  ru: "Доступно",
  pt: "Disponível",
};

function withLaunchedStatuses(copy: typeof siteCopy.en, locale: Locale): typeof siteCopy.en {
  const status = launchedStatus[locale] ?? launchedStatus.en;

  return {
    ...copy,
    productCards: {
      energyflow: { ...copy.productCards.energyflow, status },
      deskhaven: { ...copy.productCards.deskhaven, status },
      adhd: { ...copy.productCards.adhd, status },
    },
    energyflow: { ...copy.energyflow, status },
    deskhaven: { ...copy.deskhaven, status },
    adhd: { ...copy.adhd, status },
  };
}

export function getSiteCopy(locale: Locale) {
  const copy = locale === "zh"
    ? siteCopy.zh
    : {
      ...(localized[locale] ?? siteCopy.en),
      ...(productLocaleCopy[locale] ?? {}),
    };

  return withLaunchedStatuses(copy as typeof siteCopy.en, locale);
}
