import type { Locale } from "@/lib/i18n/context";

export const navCopy = {
  zh: { home: "首页", about: "关于", products: "产品", contact: "联系", language: "选择语言" },
  en: { home: "Home", about: "About", products: "Products", contact: "Contact", language: "Select language" },
  ja: { home: "ホーム", about: "概要", products: "製品", contact: "連絡", language: "言語を選択" },
  ko: { home: "홈", about: "소개", products: "제품", contact: "연락", language: "언어 선택" },
  fr: { home: "Accueil", about: "À propos", products: "Produits", contact: "Contact", language: "Choisir la langue" },
  de: { home: "Start", about: "Über uns", products: "Produkte", contact: "Kontakt", language: "Sprache wählen" },
  es: { home: "Inicio", about: "Acerca de", products: "Productos", contact: "Contacto", language: "Elegir idioma" },
};

export const siteCopy = {
  zh: {
    common: {
      productPromise: "产品承诺",
      experienceFlow: "体验流程",
      productIndex: "产品索引",
      operatingPrinciples: "工作原则",
      designPrinciples: "设计原则",
      step: "步骤",
      viewProducts: "查看产品",
      contact: "联系",
      getUpdates: "获取更新",
      microsoftStore: "Microsoft Store",
      privacy: "隐私政策",
      backToProducts: "返回产品",
    },
    home: {
      eyebrow: "独立桌面软件工作室",
      title: "为专注工作打造安静的桌面工具。",
      intro: "SoloCraft 是 Chicken Fillet 的产品主页。我做小而克制的 Windows 桌面软件：记录精力、保护专注、整理桌面，并尽量不打扰用户。",
      primary: "滚动了解理念",
      secondary: "查看产品",
      currentProduct: "产品预览",
      notes: [
        ["本地优先", "数据默认留在设备上，除非真的有必要离开。"],
        ["低摩擦", "工具应该在需要时出现，完成后安静退场。"],
        ["克制界面", "不要焦虑徽章，不要假紧迫感，不要让界面大喊大叫。"],
      ],
      chapters: [
        {
          id: "energyflow",
          num: "01 / EnergyFlow",
          title: "看清每一天精力流向。",
          body: "3 秒打卡精力，记录等级、状态、来源与心情。它不是另一张工作量表，而是帮你发现会议、任务和节奏如何影响表现。",
          bullets: ["5 级精力等级", "职场场景", "Pearson + 卡方", "本地隐私优先"],
        },
        {
          id: "deskhaven",
          num: "02 / DeskHaven",
          title: "让混乱桌面重新变成工作台。",
          body: "DeskHaven 是桌面文件避风港：守护每一份文件，让重要内容有一个安静、可控、本地安全的工作台。",
          bullets: ["本地内容空间", "关系图谱", "文件仓", "AES-256"],
        },
        {
          id: "adhd",
          num: "03 / ADHD Focus Timer",
          title: "不惩罚注意力的专注工具。",
          body: "正向计时、呼吸过渡、想法冰箱和全屏专注环境。它不催促你完成任务，而是帮你更温和地进入状态。",
          bullets: ["正向计时", "呼吸引导", "想法冰箱", "本地隐私"],
        },
      ],
      principlesTitle: "设计成不打扰人的工具。",
      principlesBody: "首页只介绍我是谁、做什么、产品气质是什么。完整产品说明、真实截图、隐私政策和下载入口都放进独立产品页。",
      productTitle: "清晰入口，而不是拥挤详情。",
      studioTitle: "小工具，也应该认真设计。",
      studioBody: "这些产品服务于同一个方向：把桌面工作从噪音、混乱和压力中稍微解放出来。",
      studioNote: "每个产品页承载真实截图、详细介绍、下载入口和隐私政策。首页只保持安静、清晰和可信。",
    },
    products: {
      eyebrow: "产品索引",
      title: "选择一个工具，进入它的完整产品页。",
      intro: "这里保留清晰的产品入口。完整介绍、真实截图、隐私信息和下载链接都放在对应产品页里。",
    },
    productCards: {
      energyflow: {
        title: "EnergyFlow",
        category: "职场能量仪表盘",
        description: "3 秒打卡精力，记录工作状态、能量来源与情绪，并用统计分析帮你看清哪些场景消耗或补充精力。",
        status: "预览",
      },
      deskhaven: {
        title: "DeskHaven",
        category: "桌面文件避风港",
        description: "守护你的每一份文件：本地私有工作台、文件仓、关系图谱、隐私加密和可控的桌面整理体验。",
        status: "开发中",
      },
      adhd: {
        title: "ADHD Focus Timer",
        category: "低压力专注计时器",
        description: "正向计时、呼吸过渡、想法冰箱和沉浸式专注环境，让进入状态更温和。",
        status: "即将推出",
      },
    },
    energyflow: {
      eyebrow: "EnergyFlow / 职场能量仪表盘",
      title: "看清工作日里，精力到底流向哪里。",
      intro: "3 秒打卡精力，5 级精力等级，记录工作状态、能量来源与情绪。EnergyFlow 用数据帮你回答：哪个会议让你耗竭？哪类任务让你充电？",
      status: "预览中",
      promiseTitle: "不是又一个待办工具，而是一块能量仪表盘。",
      promise: "EnergyFlow 的重点不是逼你更努力，而是帮你看见工作节奏的真实代价。开会、加班、深度工作、摸鱼、午休，不同场景如何消耗或恢复精力，应该由数据慢慢说清楚。",
      features: [
        ["3 秒打卡", "用最少步骤记录 5 级精力、工作状态、能量来源和心情，不把追踪本身变成负担。"],
        ["深浅模式", "深色模式适合专注，浅色模式适合日间办公。界面保持克制，不用视觉噪音抢走注意力。"],
        ["桌面常驻", "桌面悬浮入口和快捷键让记录可以随手完成：出现、记录、收起，尽量不打断当前工作。"],
        ["统计洞察", "通过 Pearson 相关和卡方检验观察能量与场景之间的关系，用长期记录发现真正的消耗源。"],
        ["隐私保护", "精力状态属于敏感个人数据。EnergyFlow 以本地优先、隐私优先为默认设计方向。"],
      ],
      flow: ["记录当下状态", "积累工作场景", "查看能量趋势", "调整工作节奏"],
    },
    deskhaven: {
      eyebrow: "DeskHaven / 桌面文件避风港",
      title: "守护你的每一份文件。",
      intro: "DeskHaven 是一个本地优先的 Windows 桌面整理工具：给零散文件一个私有工作台，用文件仓、关系图谱、隐私控制和自动化后台，让桌面重新变得安静、可控、可找回。",
      status: "开发中",
      promiseTitle: "A private desk：给重要内容一个专属工作台。",
      promise: "DeskHaven 的重点不是把文件藏起来，而是让内容之间的关系更清晰。文件仓负责安全归拢，关系图谱负责理解连接，隐私页负责密钥和控制权，设置页负责后台自动化。",
      features: [
        ["先看全局，再进入细节", "仪表盘汇总文件数量、关系数量、加密状态和存储趋势，让用户第一眼知道桌面内容是否可控。"],
        ["文件仓：把内容放回秩序里", "文件仓集中管理本地文件、元数据和归档状态。它不是云盘，而是本机内容的安静收纳层。"],
        ["关系图谱：看见内容之间的连接", "文件、标签、主题、项目之间的关系可以被看见。用户不只是找文件，也能理解文件为什么重要。"],
        ["隐私与控制权", "密钥、导入导出、加密和控制选项放在清晰位置。重要数据应该由用户掌握。"],
        ["让整理在后台自动发生", "后台自动化、路径、开关和语言设置集中在设置页，整理不应该变成每天必须维护的新系统。"],
      ],
      principles: [
        ["本地优先", "重要文件和索引默认在本机处理。"],
        ["安全可控", "用户必须知道文件在哪里，也能随时导出或找回。"],
        ["关系可视", "文件不是孤立物，项目、标签和内容关系应该可以被理解。"],
        ["低打扰", "整理应该顺手发生，而不是制造新的负担。"],
      ],
    },
    adhd: {
      eyebrow: "ADHD Focus Timer / 低压力专注",
      title: "不惩罚注意力，而是温和地进入状态。",
      intro: "ADHD Focus Timer 是一个沉浸式专注工具：呼吸过渡、正向计时、粒子陪伴、想法冰箱和本地隐私，帮助你低摩擦地开始一段专注。",
      status: "即将推出",
      promiseTitle: "专注不应该像倒计时惩罚。",
      promise: "传统计时器很容易制造压力。这个工具把重点放在进入状态、延续状态和接住分心，而不是责备分心本身。",
      features: [
        ["进入前先降噪", "介绍弹窗和准备页让用户知道接下来会发生什么，降低开始任务时的心理阻力。"],
        ["准备，而不是逼迫", "时长、白噪音、语言、呼吸引导都在开始前确定，减少专注过程中的额外选择。"],
        ["呼吸过渡", "正式开始前用呼吸引导完成从混乱到专注的切换。"],
        ["正向计时", "计时向前累积，而不是倒数制造失败感。粒子和进度给出轻微陪伴。"],
        ["想法冰箱", "突然冒出的想法不需要立刻处理，可以先放进冰箱，之后再回来。"],
        ["完成反馈", "结束不是审判，而是记录一次真实完成。成就页面给出温和反馈。"],
        ["支持与隐私", "工具保持本地优先、最小数据、清晰隐私说明，避免把专注数据变成另一种压力。"],
      ],
    },
    about: {
      title: "关于 SoloCraft",
      intro: "SoloCraft 是 Chicken Fillet 的独立桌面软件工作室，专注于安静、克制、隐私优先的小工具。",
      story: [
        "我喜欢做那些不抢戏的工具：它们应该在需要时出现，在完成后退到背景里。",
        "EnergyFlow、DeskHaven 和 ADHD Focus Timer 都围绕同一个问题：怎样让桌面工作更可恢复、更可理解、更少压力。",
        "这个网站是产品入口，也是一个小小的设计宣言：真实截图、清晰文案、少一点噪音，多一点信任。",
      ],
      philosophyTitle: "设计原则",
      philosophy: [
        ["小而完整", "每个工具聚焦一个明确场景，但把关键流程做完整。"],
        ["桌面原生", "围绕真实桌面工作流，而不是把网页仪表盘硬塞进应用。"],
        ["克制表达", "视觉服务于理解，不用装饰制造廉价兴奋。"],
        ["隐私优先", "能留在本地的数据，就不轻易离开设备。"],
      ],
      techTitle: "技术方向",
      tech: ["Windows desktop apps", "Local-first storage", "Statistics and visualization", "Privacy-conscious product design"],
      ctaTitle: "想聊产品、合作或反馈？",
      ctaDescription: "我会认真阅读每一封真实来信。",
      ctaButton: "联系我",
    },
    contact: {
      title: "联系",
      intro: "产品反馈、合作想法、媒体询问或单纯打个招呼，都可以发邮件给我。",
      infoTitle: "联系方式",
      email: "邮箱",
    },
    footer: {
      subtitle: "Chicken Fillet 的独立桌面软件工作室。",
      studio: "工作室",
      products: "产品",
      legal: "法务",
      about: "关于",
      contact: "联系",
      privacy: "隐私政策",
      copyright: "安静、克制、隐私优先的桌面工具。",
    },
  },
  en: {
    common: {
      productPromise: "Product promise",
      experienceFlow: "Experience flow",
      productIndex: "Product index",
      operatingPrinciples: "Operating principles",
      designPrinciples: "Design principles",
      step: "Step",
      viewProducts: "View products",
      contact: "Contact",
      getUpdates: "Get updates",
      microsoftStore: "Microsoft Store",
      privacy: "Privacy policy",
      backToProducts: "Back to products",
    },
    home: {
      eyebrow: "Independent desktop software studio",
      title: "Quiet tools for focused desktop work.",
      intro: "SoloCraft is the product home for Chicken Fillet: small, restrained Windows desktop tools for tracking energy, protecting focus, and keeping the desktop calm.",
      primary: "Scroll the story",
      secondary: "View products",
      currentProduct: "Product preview",
      notes: [
        ["Local-first", "Data stays on the device unless there is a clear reason to leave."],
        ["Low-friction", "Tools appear when needed, then step away."],
        ["Calm UI", "No fake urgency, no noisy badges, no anxiety loops."],
      ],
      chapters: [
        { id: "energyflow", num: "01 / EnergyFlow", title: "Understand where your energy goes.", body: "Capture energy in seconds, then see how meetings, tasks, overtime, and recovery shape the way you work.", bullets: ["5-level energy state", "Work context", "Pearson + Chi-square", "Local privacy"] },
        { id: "deskhaven", num: "02 / DeskHaven", title: "A quiet haven for every file.", body: "DeskHaven gives local files a private desk: a calm, controllable workspace with vaults, maps, and recovery-friendly organization.", bullets: ["Private desk", "Relationship map", "File vault", "AES-256"] },
        { id: "adhd", num: "03 / ADHD Focus Timer", title: "Focus without punishment.", body: "Forward timing, breathing transition, idea parking, and a calm full-screen focus environment for low-resistance sessions.", bullets: ["Forward timer", "Breathing guide", "Idea Fridge", "Local privacy"] },
      ],
      principlesTitle: "Designed to stay out of the way.",
      principlesBody: "The home page introduces the studio and product philosophy. Detailed product stories, real screenshots, policies, and calls to action live on individual product pages.",
      productTitle: "Clear entrances, not crowded detail.",
      studioTitle: "Small tools, built with restraint.",
      studioBody: "These products share one direction: making desktop work quieter, more recoverable, and less stressful.",
      studioNote: "Each product page carries real screenshots, product details, downloads, and privacy links. The home page stays quiet, clear, and trustworthy.",
    },
    products: {
      eyebrow: "Product index",
      title: "Choose a tool and open its full product page.",
      intro: "This page keeps the product entrances clear. Full stories, real screenshots, privacy details, and download links live on each product page.",
    },
    productCards: {
      energyflow: { title: "EnergyFlow", category: "Workplace energy dashboard", description: "Capture energy in seconds, record work state and energy source, then use statistical insight to understand what drains or restores you.", status: "Preview" },
      deskhaven: { title: "DeskHaven", category: "Desktop file haven", description: "A private desk for every file: local vaults, relationship maps, privacy controls, and a calm place for desktop organization.", status: "In development" },
      adhd: { title: "ADHD Focus Timer", category: "Low-pressure focus timer", description: "Forward timing, breathing transition, Idea Fridge, and a calm full-screen focus environment for low-resistance sessions.", status: "Coming soon" },
    },
    energyflow: {
      eyebrow: "EnergyFlow / Workplace Energy Dashboard",
      title: "Understand where your workday energy goes.",
      intro: "Capture energy in three seconds with a five-level state, work context, energy source, and mood. EnergyFlow helps answer which meetings drain you and which tasks restore you.",
      status: "Preview",
      promiseTitle: "Not another task app. A dashboard for your energy rhythm.",
      promise: "EnergyFlow is not about pushing you to work harder. It helps you see the hidden cost of your rhythm: meetings, overtime, deep work, breaks, and the moments that quietly shape performance.",
      features: [
        ["Three-second logging", "Record energy level, work status, energy source, and mood with minimal friction."],
        ["Dark or light clarity", "Deep mode for focus and light mode for daytime work, without loud interface noise."],
        ["Always on desktop", "A floating entry and hotkey make logging appear, record, and disappear without breaking flow."],
        ["Statistical insight", "Pearson correlation and Chi-square analysis help reveal which contexts really affect energy."],
        ["Privacy protection", "Energy state data is sensitive. EnergyFlow is designed with local-first privacy as the default."],
      ],
      flow: ["Capture state", "Accumulate context", "Review energy patterns", "Adjust work rhythm"],
    },
    deskhaven: {
      eyebrow: "DeskHaven / Desktop File Haven",
      title: "A private desk for every file.",
      intro: "DeskHaven is a local-first Windows desktop organization tool: a private desk for loose files, with vaults, relationship maps, privacy controls, and background automation.",
      status: "In development",
      promiseTitle: "A calm workspace for content, not a noisy file manager.",
      promise: "DeskHaven is not about hiding files. It helps users understand local content. The vault gathers files safely, the relationship map reveals connections, privacy controls keep ownership clear, and settings keep automation understandable.",
      features: [
        ["Overview before detail", "The dashboard summarizes file count, relationships, encryption state, and storage trends so users know whether their desktop is under control."],
        ["File vault", "The vault manages local files, metadata, and archive state. It is a quiet local layer, not another cloud drive."],
        ["Relationship map", "Files, tags, topics, and projects can be seen as relationships. Users do not only find files; they understand why files matter."],
        ["Privacy and control", "Keys, import, export, encryption, and control options live in one clear place. Important data should remain under user control."],
        ["Automation that stays quiet", "Background automation, paths, switches, and language settings are grouped clearly, so cleanup does not become another daily system."],
      ],
      principles: [
        ["Local-first", "Important files and indexes are handled locally by default."],
        ["Controlled", "Users should know where files are and how to recover them."],
        ["Relational", "Projects, tags, and content connections should be understandable."],
        ["Low-friction", "Organization should happen naturally without becoming a new burden."],
      ],
    },
    adhd: {
      eyebrow: "ADHD Focus Timer / Low-pressure focus",
      title: "Focus without turning attention into a trial.",
      intro: "ADHD Focus Timer is an immersive focus tool with breathing transition, forward timing, particle companionship, Idea Fridge, and local-first privacy.",
      status: "Coming soon",
      promiseTitle: "Focus should not feel like punishment by countdown.",
      promise: "A timer can easily become pressure. This product focuses on entering a session, sustaining it gently, and catching distractions without blaming the user.",
      features: [
        ["Lower the noise first", "The intro and preparation screens explain what will happen next, reducing resistance before a task begins."],
        ["Prepare, do not pressure", "Duration, white noise, language, and breathing are selected before focus starts to reduce mid-session choices."],
        ["Breathing transition", "A short breathing guide helps shift from scattered attention into a focused state."],
        ["Forward timing", "Time accumulates forward instead of counting down toward failure. Particles and progress provide quiet companionship."],
        ["Idea Fridge", "Unexpected thoughts can be parked without being obeyed immediately, then revisited after the session."],
        ["Gentle completion", "Ending a session is not a judgment. The achievement screen records a real completion with soft feedback."],
        ["Support and privacy", "Local-first behavior, minimal data, and clear privacy language keep focus data from becoming another source of pressure."],
      ],
    },
    about: {
      title: "About SoloCraft",
      intro: "SoloCraft is Chicken Fillet's independent desktop software studio for quiet, restrained, privacy-first tools.",
      story: [
        "I like tools that do not steal the stage. They should appear when needed and return to the background when the work is done.",
        "EnergyFlow, DeskHaven, and ADHD Focus Timer all circle the same question: how can desktop work become more recoverable, understandable, and less stressful?",
        "This site is a product entrance and a small design statement: real screenshots, clear copy, less noise, more trust.",
      ],
      philosophyTitle: "Design principles",
      philosophy: [
        ["Small and complete", "Each tool focuses on a clear scenario while completing the important workflow."],
        ["Desktop-native", "Built around actual desktop workflows, not another web dashboard in disguise."],
        ["Restrained", "Visual design serves understanding instead of manufacturing cheap excitement."],
        ["Privacy-first", "Data that can stay local should not leave the device lightly."],
      ],
      techTitle: "Technical direction",
      tech: ["Windows desktop apps", "Local-first storage", "Statistics and visualization", "Privacy-conscious product design"],
      ctaTitle: "Want to talk products, collaboration, or feedback?",
      ctaDescription: "I read every real note carefully.",
      ctaButton: "Contact me",
    },
    contact: {
      title: "Contact",
      intro: "Product feedback, collaboration ideas, media questions, or a simple hello can all go to email.",
      infoTitle: "Contact information",
      email: "Email",
    },
    footer: {
      subtitle: "Independent desktop software by Chicken Fillet.",
      studio: "Studio",
      products: "Products",
      legal: "Legal",
      about: "About",
      contact: "Contact",
      privacy: "Privacy Policy",
      copyright: "Quiet, restrained, privacy-first desktop tools.",
    },
  },
};

const localized: Partial<Record<Locale, typeof siteCopy.en>> = {
  ja: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "製品の約束", experienceFlow: "体験の流れ", productIndex: "製品一覧", operatingPrinciples: "運用原則", designPrinciples: "設計原則", step: "ステップ", viewProducts: "製品を見る", contact: "連絡", getUpdates: "更新を受け取る", privacy: "プライバシーポリシー", backToProducts: "製品に戻る" },
    home: { ...siteCopy.en.home, eyebrow: "独立系デスクトップソフトウェアスタジオ", title: "集中するデスクトップ作業のための静かなツール。", intro: "SoloCraft は Chicken Fillet の製品ホームです。エネルギーを記録し、集中を守り、デスクトップを落ち着かせる小さく控えめな Windows ツールを作っています。" },
    products: { eyebrow: "製品一覧", title: "ツールを選び、詳しい製品ページへ。", intro: "ここでは製品への入口を分かりやすく整理しています。詳しい紹介、実際のスクリーンショット、プライバシー情報、ダウンロードリンクは各製品ページにあります。" },
    about: { ...siteCopy.en.about, title: "SoloCraft について", intro: "SoloCraft は Chicken Fillet の独立系デスクトップソフトウェアスタジオです。静かで控えめ、プライバシーを重視したツールを作ります。" },
    contact: { title: "連絡", intro: "製品フィードバック、協業の相談、メディア問い合わせ、または短い挨拶でもメールでどうぞ。", infoTitle: "連絡先", email: "メール" },
    footer: { ...siteCopy.en.footer, studio: "スタジオ", products: "製品", legal: "法務", about: "概要", contact: "連絡", privacy: "プライバシーポリシー" },
  },
  ko: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "제품 약속", experienceFlow: "경험 흐름", productIndex: "제품 목록", operatingPrinciples: "운영 원칙", designPrinciples: "설계 원칙", step: "단계", viewProducts: "제품 보기", contact: "연락", getUpdates: "업데이트 받기", privacy: "개인정보 처리방침", backToProducts: "제품으로 돌아가기" },
    home: { ...siteCopy.en.home, eyebrow: "독립 데스크톱 소프트웨어 스튜디오", title: "집중하는 데스크톱 작업을 위한 조용한 도구.", intro: "SoloCraft는 Chicken Fillet의 제품 홈입니다. 에너지를 기록하고, 집중을 보호하고, 데스크톱을 차분하게 만드는 작고 절제된 Windows 도구를 만듭니다." },
    products: { eyebrow: "제품 목록", title: "도구를 선택하고 전체 제품 페이지로 이동하세요.", intro: "이 페이지는 제품 입구를 명확하게 정리합니다. 자세한 소개, 실제 스크린샷, 개인정보 정보와 다운로드 링크는 각 제품 페이지에 있습니다." },
    about: { ...siteCopy.en.about, title: "SoloCraft 소개", intro: "SoloCraft는 Chicken Fillet의 독립 데스크톱 소프트웨어 스튜디오로, 조용하고 절제되며 개인정보를 우선하는 도구를 만듭니다." },
    contact: { title: "연락", intro: "제품 피드백, 협업 아이디어, 미디어 문의 또는 짧은 인사도 이메일로 보내 주세요.", infoTitle: "연락처", email: "이메일" },
    footer: { ...siteCopy.en.footer, studio: "스튜디오", products: "제품", legal: "법무", about: "소개", contact: "연락", privacy: "개인정보 처리방침" },
  },
  fr: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "Promesse produit", experienceFlow: "Parcours", productIndex: "Index des produits", operatingPrinciples: "Principes", designPrinciples: "Principes de design", step: "Étape", viewProducts: "Voir les produits", contact: "Contact", getUpdates: "Recevoir les nouvelles", privacy: "Confidentialité", backToProducts: "Retour aux produits" },
    home: { ...siteCopy.en.home, eyebrow: "Studio indépendant de logiciels desktop", title: "Des outils calmes pour le travail concentré.", intro: "SoloCraft est la maison produit de Chicken Fillet : de petits outils Windows sobres pour suivre l'énergie, protéger la concentration et apaiser le bureau." },
    products: { eyebrow: "Index des produits", title: "Choisissez un outil et ouvrez sa page complète.", intro: "Cette page garde les entrées produit claires. Les présentations complètes, captures réelles, détails de confidentialité et liens de téléchargement se trouvent sur chaque page produit." },
    about: { ...siteCopy.en.about, title: "À propos de SoloCraft", intro: "SoloCraft est le studio indépendant de Chicken Fillet pour des outils desktop calmes, sobres et respectueux de la vie privée." },
    contact: { title: "Contact", intro: "Retours produit, idées de collaboration, demandes presse ou simple bonjour peuvent arriver par e-mail.", infoTitle: "Coordonnées", email: "E-mail" },
    footer: { ...siteCopy.en.footer, studio: "Studio", products: "Produits", legal: "Mentions", about: "À propos", contact: "Contact", privacy: "Confidentialité" },
  },
  de: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "Produktversprechen", experienceFlow: "Ablauf", productIndex: "Produktübersicht", operatingPrinciples: "Arbeitsprinzipien", designPrinciples: "Designprinzipien", step: "Schritt", viewProducts: "Produkte ansehen", contact: "Kontakt", getUpdates: "Updates erhalten", privacy: "Datenschutz", backToProducts: "Zurück zu Produkten" },
    home: { ...siteCopy.en.home, eyebrow: "Unabhängiges Desktop-Softwarestudio", title: "Ruhige Werkzeuge für fokussierte Desktop-Arbeit.", intro: "SoloCraft ist die Produktseite von Chicken Fillet: kleine, zurückhaltende Windows-Tools zum Erfassen von Energie, Schützen von Fokus und Beruhigen des Desktops." },
    products: { eyebrow: "Produktübersicht", title: "Wähle ein Tool und öffne die vollständige Produktseite.", intro: "Diese Seite hält die Produkteinstiege klar. Ausführliche Beschreibungen, echte Screenshots, Datenschutzdetails und Downloadlinks stehen auf den jeweiligen Produktseiten." },
    about: { ...siteCopy.en.about, title: "Über SoloCraft", intro: "SoloCraft ist Chicken Fillets unabhängiges Studio für ruhige, zurückhaltende und datenschutzbewusste Desktop-Tools." },
    contact: { title: "Kontakt", intro: "Produktfeedback, Kooperationsideen, Medienanfragen oder ein kurzes Hallo können per E-Mail kommen.", infoTitle: "Kontaktinformationen", email: "E-Mail" },
    footer: { ...siteCopy.en.footer, studio: "Studio", products: "Produkte", legal: "Rechtliches", about: "Über uns", contact: "Kontakt", privacy: "Datenschutz" },
  },
  es: {
    ...siteCopy.en,
    common: { ...siteCopy.en.common, productPromise: "Promesa del producto", experienceFlow: "Flujo de experiencia", productIndex: "Índice de productos", operatingPrinciples: "Principios", designPrinciples: "Principios de diseño", step: "Paso", viewProducts: "Ver productos", contact: "Contacto", getUpdates: "Recibir novedades", privacy: "Privacidad", backToProducts: "Volver a productos" },
    home: { ...siteCopy.en.home, eyebrow: "Estudio independiente de software de escritorio", title: "Herramientas tranquilas para trabajar con foco.", intro: "SoloCraft es el hogar de productos de Chicken Fillet: pequeñas herramientas de Windows, sobrias, para registrar energía, proteger el foco y mantener el escritorio en calma." },
    products: { eyebrow: "Índice de productos", title: "Elige una herramienta y abre su página completa.", intro: "Esta página mantiene claras las entradas de producto. Las descripciones completas, capturas reales, detalles de privacidad y enlaces de descarga están en cada página de producto." },
    about: { ...siteCopy.en.about, title: "Acerca de SoloCraft", intro: "SoloCraft es el estudio independiente de Chicken Fillet para herramientas de escritorio tranquilas, sobrias y centradas en la privacidad." },
    contact: { title: "Contacto", intro: "Comentarios de producto, ideas de colaboración, consultas de prensa o un simple saludo pueden llegar por correo.", infoTitle: "Información de contacto", email: "Correo" },
    footer: { ...siteCopy.en.footer, studio: "Estudio", products: "Productos", legal: "Legal", about: "Acerca de", contact: "Contacto", privacy: "Privacidad" },
  },
};

const productLocaleCopy: Partial<Record<Locale, Pick<typeof siteCopy.en, "productCards" | "energyflow" | "deskhaven" | "adhd">>> = {
  ja: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "仕事のエネルギーダッシュボード", description: "数秒でエネルギーを記録し、仕事の状態や回復源を統計的に見える化します。", status: "プレビュー" },
      deskhaven: { title: "DeskHaven", category: "デスクトップファイルの避難所", description: "ローカルの保管庫、関係マップ、プライバシー制御で、散らばったファイルに静かな作業台を作ります。", status: "開発中" },
      adhd: { title: "ADHD Focus Timer", category: "低圧の集中タイマー", description: "前向きな計時、呼吸の移行、Idea Fridge、落ち着いた全画面集中環境。", status: "近日公開" },
    },
    energyflow: {
      ...siteCopy.en.energyflow,
      eyebrow: "EnergyFlow / 仕事のエネルギーダッシュボード",
      title: "仕事日のエネルギーがどこへ流れるかを見る。",
      intro: "5 段階のエネルギー、仕事の文脈、回復源、気分を数秒で記録します。EnergyFlow は、消耗する会議や回復するタスクを見つけるための道具です。",
      status: "プレビュー",
      promiseTitle: "タスクアプリではなく、エネルギーリズムの計器盤。",
      promise: "もっと働かせるためではなく、会議、残業、深い作業、休憩が集中力に与える本当のコストを見るための製品です。",
      features: [
        ["3 秒ログ", "エネルギー、状態、回復源、気分を少ない操作で記録します。"],
        ["明暗モード", "集中用のダークモードと日中作業用のライトモード。"],
        ["デスクトップ常駐", "フローティング入口とショートカットで流れを止めずに記録します。"],
        ["統計洞察", "相関とカイ二乗検定で、文脈とエネルギーの関係を観察します。"],
        ["プライバシー保護", "エネルギーデータは個人的です。ローカル優先を基本に設計しています。"],
      ],
      flow: ["状態を記録", "文脈を蓄積", "傾向を確認", "働き方を調整"],
    },
    deskhaven: {
      ...siteCopy.en.deskhaven,
      eyebrow: "DeskHaven / デスクトップファイルの避難所",
      title: "すべてのファイルに私的な作業台を。",
      intro: "DeskHaven はローカル優先の Windows デスクトップ整理ツールです。保管庫、関係マップ、プライバシー制御、自動化で、散らばったファイルを落ち着いた状態に戻します。",
      status: "開発中",
      promiseTitle: "うるさいファイル管理ではなく、内容のための静かな場所。",
      promise: "ファイルを隠すのではなく、関係を理解しやすくします。保管庫、関係マップ、プライバシー制御、設定がそれぞれ役割を持ちます。",
      features: [
        ["まず全体を見る", "ダッシュボードでファイル数、関係、暗号化状態、保存傾向を確認します。"],
        ["ファイル保管庫", "ローカルファイル、メタデータ、アーカイブ状態を静かに管理します。"],
        ["関係マップ", "ファイル、タグ、テーマ、プロジェクトのつながりを見える化します。"],
        ["プライバシーと制御", "鍵、インポート、エクスポート、暗号化を分かりやすく配置します。"],
        ["静かな自動化", "整理は背景で自然に行われ、毎日の負担になりません。"],
      ],
      principles: [
        ["ローカル優先", "重要なファイルと索引は基本的に端末内で処理します。"],
        ["制御可能", "ファイルの場所と復元方法を利用者が把握できます。"],
        ["関係を見る", "タグやプロジェクトとのつながりを理解できます。"],
        ["低摩擦", "整理が新しい負担にならないようにします。"],
      ],
    },
    adhd: {
      ...siteCopy.en.adhd,
      eyebrow: "ADHD Focus Timer / 低圧の集中",
      title: "注意力を裁かず、やさしく集中へ入る。",
      intro: "呼吸の移行、前向きな計時、粒子の伴走、Idea Fridge、ローカル優先のプライバシーを備えた集中ツールです。",
      status: "近日公開",
      promiseTitle: "集中はカウントダウンの罰であるべきではありません。",
      promise: "タイマーは圧力になりがちです。この製品は開始、継続、分心の受け止めをやさしく支えます。",
      features: [
        ["先にノイズを下げる", "開始前に流れを説明し、心理的抵抗を減らします。"],
        ["準備する", "時間、音、言語、呼吸を先に選びます。"],
        ["呼吸の移行", "短い呼吸ガイドで状態を切り替えます。"],
        ["前向きな計時", "時間を積み上げ、失敗感を避けます。"],
        ["Idea Fridge", "浮かんだ考えを一時的に置いておけます。"],
        ["やさしい完了", "終了は評価ではなく、実際の完了記録です。"],
        ["支援とプライバシー", "最小データとローカル優先で、集中データを負担にしません。"],
      ],
    },
  },
  ko: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "업무 에너지 대시보드", description: "몇 초 만에 에너지를 기록하고 업무 상태와 회복 요인을 통계로 이해합니다.", status: "미리보기" },
      deskhaven: { title: "DeskHaven", category: "데스크톱 파일 안식처", description: "로컬 보관함, 관계 지도, 개인정보 제어로 흩어진 파일에 조용한 작업대를 만듭니다.", status: "개발 중" },
      adhd: { title: "ADHD Focus Timer", category: "저압 집중 타이머", description: "정방향 타이머, 호흡 전환, Idea Fridge, 차분한 전체 화면 집중 환경.", status: "출시 예정" },
    },
    energyflow: { ...siteCopy.en.energyflow, eyebrow: "EnergyFlow / 업무 에너지 대시보드", title: "업무 에너지가 어디로 흐르는지 이해하세요.", intro: "5단계 에너지, 업무 맥락, 회복 요인, 기분을 몇 초 안에 기록합니다.", status: "미리보기", promiseTitle: "또 하나의 할 일 앱이 아니라 에너지 리듬 대시보드.", promise: "더 열심히 일하게 만드는 도구가 아니라 회의, 야근, 깊은 작업, 휴식이 에너지에 미치는 비용을 보여줍니다.", features: [["3초 기록", "최소한의 마찰로 에너지와 맥락을 남깁니다."], ["명암 모드", "집중과 낮 시간 업무에 맞는 차분한 화면."], ["데스크톱 상주", "떠 있는 진입점과 단축키로 흐름을 끊지 않습니다."], ["통계 인사이트", "상관과 카이제곱으로 맥락의 영향을 봅니다."], ["개인정보 보호", "에너지 데이터는 민감하므로 로컬 우선을 기본으로 합니다."]], flow: ["상태 기록", "맥락 축적", "패턴 확인", "리듬 조정"] },
    deskhaven: { ...siteCopy.en.deskhaven, eyebrow: "DeskHaven / 데스크톱 파일 안식처", title: "모든 파일을 위한 개인 작업대.", intro: "DeskHaven은 로컬 우선 Windows 데스크톱 정리 도구입니다. 보관함, 관계 지도, 개인정보 제어, 자동화로 파일을 차분하게 정리합니다.", status: "개발 중", promiseTitle: "시끄러운 파일 관리자가 아닌 조용한 콘텐츠 작업공간.", promise: "파일을 숨기는 것이 아니라 관계를 이해하게 돕습니다.", features: [["전체를 먼저 보기", "대시보드가 파일 수, 관계, 암호화 상태, 저장 추세를 요약합니다."], ["파일 보관함", "로컬 파일과 메타데이터를 조용히 관리합니다."], ["관계 지도", "파일, 태그, 주제, 프로젝트의 연결을 봅니다."], ["개인정보와 제어", "키, 가져오기, 내보내기, 암호화를 명확히 둡니다."], ["조용한 자동화", "정리가 매일의 새 부담이 되지 않게 합니다."]], principles: [["로컬 우선", "중요한 파일과 색인은 기본적으로 로컬에서 처리합니다."], ["제어 가능", "파일 위치와 복구 방법을 알 수 있습니다."], ["관계 중심", "프로젝트와 태그의 연결을 이해합니다."], ["낮은 마찰", "정리가 자연스럽게 일어납니다."]] },
    adhd: { ...siteCopy.en.adhd, eyebrow: "ADHD Focus Timer / 저압 집중", title: "주의력을 벌하지 않고 부드럽게 상태에 들어가기.", intro: "호흡 전환, 정방향 타이머, 입자 동반, Idea Fridge, 로컬 우선 개인정보를 갖춘 집중 도구입니다.", status: "출시 예정", promiseTitle: "집중은 카운트다운 처벌처럼 느껴져서는 안 됩니다.", promise: "이 도구는 시작, 지속, 산만함을 받아 주는 데 초점을 둡니다.", features: [["먼저 소음 낮추기", "시작 전 흐름을 알려 저항을 줄입니다."], ["준비하기", "시간, 소리, 언어, 호흡을 먼저 정합니다."], ["호흡 전환", "짧은 호흡 가이드로 상태를 바꿉니다."], ["정방향 타이머", "시간을 쌓아 실패감을 줄입니다."], ["Idea Fridge", "떠오른 생각을 잠시 보관합니다."], ["부드러운 완료", "끝은 평가가 아니라 실제 완료 기록입니다."], ["지원과 개인정보", "최소 데이터와 로컬 우선으로 부담을 줄입니다."]] },
  },
  fr: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "Tableau d'énergie au travail", description: "Notez votre énergie en quelques secondes et comprenez ce qui vous épuise ou vous restaure.", status: "Aperçu" },
      deskhaven: { title: "DeskHaven", category: "Havre de fichiers desktop", description: "Un bureau privé pour chaque fichier, avec coffres locaux, cartes de relations et contrôles de confidentialité.", status: "En développement" },
      adhd: { title: "ADHD Focus Timer", category: "Minuteur de concentration doux", description: "Chronométrage progressif, respiration, Idea Fridge et environnement plein écran apaisé.", status: "Bientôt" },
    },
    energyflow: { ...siteCopy.en.energyflow, eyebrow: "EnergyFlow / Tableau d'énergie au travail", title: "Comprendre où va votre énergie de travail.", intro: "Enregistrez en quelques secondes votre niveau d'énergie, le contexte, la source et l'humeur.", status: "Aperçu", promiseTitle: "Pas une autre app de tâches, mais un tableau pour votre rythme.", promise: "EnergyFlow aide à voir le coût réel des réunions, heures longues, travail profond et pauses.", features: [["Journal en trois secondes", "Enregistrez énergie, état, source et humeur avec peu de friction."], ["Clarté sombre ou claire", "Modes sobres pour concentration ou travail de jour."], ["Présent sur le bureau", "Entrée flottante et raccourci sans casser le flux."], ["Analyse statistique", "Corrélations et khi carré révèlent les contextes qui comptent."], ["Confidentialité", "Les données d'énergie restent pensées localement par défaut."]], flow: ["Capturer l'état", "Accumuler le contexte", "Lire les tendances", "Ajuster le rythme"] },
    deskhaven: { ...siteCopy.en.deskhaven, eyebrow: "DeskHaven / Havre de fichiers desktop", title: "Un bureau privé pour chaque fichier.", intro: "DeskHaven est un outil Windows local-first pour organiser les fichiers avec coffres, relations, confidentialité et automatisation.", status: "En développement", promiseTitle: "Un espace calme pour le contenu, pas un gestionnaire bruyant.", promise: "DeskHaven ne cache pas les fichiers : il rend leurs liens plus compréhensibles.", features: [["Vue d'ensemble", "Le tableau résume fichiers, relations, chiffrement et stockage."], ["Coffre de fichiers", "Une couche locale calme pour fichiers et métadonnées."], ["Carte de relations", "Voir les liens entre fichiers, tags, sujets et projets."], ["Confidentialité et contrôle", "Clés, import, export et chiffrement restent lisibles."], ["Automatisation discrète", "Le rangement se fait en arrière-plan sans nouvelle charge."]], principles: [["Local-first", "Les fichiers importants sont traités localement par défaut."], ["Contrôlé", "L'utilisateur sait où sont les fichiers et comment les récupérer."], ["Relationnel", "Les liens entre projets, tags et contenus restent visibles."], ["Faible friction", "L'organisation ne devient pas une nouvelle charge."]] },
    adhd: { ...siteCopy.en.adhd, eyebrow: "ADHD Focus Timer / Concentration douce", title: "Se concentrer sans transformer l'attention en procès.", intro: "Un outil immersif avec respiration, chronométrage progressif, particules, Idea Fridge et confidentialité locale.", status: "Bientôt", promiseTitle: "La concentration ne devrait pas ressembler à une punition.", promise: "Le produit aide à entrer, rester et accueillir les distractions sans culpabiliser.", features: [["Réduire le bruit", "Les écrans d'introduction diminuent la résistance au démarrage."], ["Préparer", "Durée, son, langue et respiration sont choisis avant la session."], ["Transition respiratoire", "Un court guide aide à changer d'état."], ["Chronométrage progressif", "Le temps s'accumule au lieu de compter vers l'échec."], ["Idea Fridge", "Les idées soudaines peuvent attendre."], ["Fin douce", "La fin enregistre une vraie complétion sans jugement."], ["Soutien et vie privée", "Peu de données, local-first, langage clair."]] },
  },
  de: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "Energie-Dashboard für Arbeit", description: "Erfasse Energie in Sekunden und verstehe, was dich erschöpft oder wieder auflädt.", status: "Vorschau" },
      deskhaven: { title: "DeskHaven", category: "Desktop-Dateihafen", description: "Ein privater Schreibtisch für jede Datei, mit lokalen Tresoren, Beziehungskarten und Datenschutzkontrolle.", status: "In Entwicklung" },
      adhd: { title: "ADHD Focus Timer", category: "Sanfter Fokus-Timer", description: "Vorwärtszählung, Atemübergang, Idea Fridge und ruhige Vollbildumgebung.", status: "Bald verfügbar" },
    },
    energyflow: { ...siteCopy.en.energyflow, eyebrow: "EnergyFlow / Energie-Dashboard", title: "Verstehe, wohin deine Arbeitsenergie geht.", intro: "Erfasse Energie, Kontext, Quelle und Stimmung in wenigen Sekunden.", status: "Vorschau", promiseTitle: "Keine weitere Aufgaben-App, sondern ein Dashboard für deinen Rhythmus.", promise: "EnergyFlow zeigt die echten Kosten von Meetings, Überstunden, Tiefenarbeit und Pausen.", features: [["Drei-Sekunden-Log", "Energie und Kontext mit wenig Reibung erfassen."], ["Hell oder dunkel", "Ruhige Modi für Fokus und Tagesarbeit."], ["Auf dem Desktop", "Schwebender Einstieg und Hotkey ohne Unterbrechung."], ["Statistische Einsicht", "Korrelation und Chi-Quadrat zeigen relevante Kontexte."], ["Datenschutz", "Energiedaten sind sensibel und lokal gedacht."]], flow: ["Zustand erfassen", "Kontext sammeln", "Muster prüfen", "Rhythmus anpassen"] },
    deskhaven: { ...siteCopy.en.deskhaven, eyebrow: "DeskHaven / Desktop-Dateihafen", title: "Ein privater Schreibtisch für jede Datei.", intro: "DeskHaven organisiert lokale Windows-Dateien mit Tresoren, Beziehungskarten, Datenschutz und Automatisierung.", status: "In Entwicklung", promiseTitle: "Ein ruhiger Arbeitsraum für Inhalte.", promise: "DeskHaven versteckt Dateien nicht, sondern macht Beziehungen verständlich.", features: [["Überblick zuerst", "Dashboard für Dateien, Beziehungen, Verschlüsselung und Speicher."], ["Dateitresor", "Lokale Dateien und Metadaten ruhig verwalten."], ["Beziehungskarte", "Verbindungen zwischen Dateien, Tags und Projekten sehen."], ["Datenschutz und Kontrolle", "Schlüssel, Import, Export und Verschlüsselung bleiben klar."], ["Leise Automatisierung", "Ordnung passiert im Hintergrund."]], principles: [["Local-first", "Wichtige Dateien bleiben standardmäßig lokal."], ["Kontrolliert", "Dateien und Wiederherstellung bleiben nachvollziehbar."], ["Relational", "Verbindungen bleiben verständlich."], ["Reibungsarm", "Ordnung wird keine neue Last."]] },
    adhd: { ...siteCopy.en.adhd, eyebrow: "ADHD Focus Timer / Sanfter Fokus", title: "Fokus, ohne Aufmerksamkeit zu bestrafen.", intro: "Ein immersives Tool mit Atemübergang, Vorwärtszählung, Partikeln, Idea Fridge und lokaler Privatsphäre.", status: "Bald verfügbar", promiseTitle: "Fokus sollte sich nicht wie Countdown-Strafe anfühlen.", promise: "Das Produkt unterstützt Einstieg, Fortsetzung und Ablenkungen ohne Schuldgefühl.", features: [["Lärm senken", "Einführung senkt Widerstand vor dem Start."], ["Vorbereiten", "Dauer, Ton, Sprache und Atmung stehen vorher fest."], ["Atemübergang", "Kurze Atemführung wechselt den Zustand."], ["Vorwärtszählung", "Zeit sammelt sich ohne Scheiternsgefühl."], ["Idea Fridge", "Gedanken können geparkt werden."], ["Sanfter Abschluss", "Ende ist Aufzeichnung, kein Urteil."], ["Support und Datenschutz", "Minimale Daten und local-first."]] },
  },
  es: {
    productCards: {
      energyflow: { title: "EnergyFlow", category: "Panel de energía laboral", description: "Registra energía en segundos y entiende qué te drena o te restaura.", status: "Vista previa" },
      deskhaven: { title: "DeskHaven", category: "Refugio de archivos de escritorio", description: "Un escritorio privado para cada archivo, con bóvedas locales, mapas de relación y privacidad.", status: "En desarrollo" },
      adhd: { title: "ADHD Focus Timer", category: "Temporizador de foco suave", description: "Conteo hacia adelante, respiración, Idea Fridge y ambiente de foco en pantalla completa.", status: "Próximamente" },
    },
    energyflow: { ...siteCopy.en.energyflow, eyebrow: "EnergyFlow / Panel de energía laboral", title: "Entiende a dónde va tu energía de trabajo.", intro: "Registra nivel de energía, contexto, fuente y ánimo en pocos segundos.", status: "Vista previa", promiseTitle: "No otra app de tareas, sino un panel para tu ritmo.", promise: "EnergyFlow muestra el costo real de reuniones, horas extra, trabajo profundo y descansos.", features: [["Registro en tres segundos", "Energía y contexto con mínima fricción."], ["Claridad clara u oscura", "Modos sobrios para foco o trabajo diurno."], ["Siempre en el escritorio", "Entrada flotante y atajo sin cortar el flujo."], ["Insight estadístico", "Correlación y chi cuadrado revelan contextos relevantes."], ["Privacidad", "Los datos de energía son sensibles y se diseñan local-first."]], flow: ["Capturar estado", "Acumular contexto", "Revisar patrones", "Ajustar ritmo"] },
    deskhaven: { ...siteCopy.en.deskhaven, eyebrow: "DeskHaven / Refugio de archivos", title: "Un escritorio privado para cada archivo.", intro: "DeskHaven organiza archivos locales de Windows con bóvedas, mapas de relación, privacidad y automatización.", status: "En desarrollo", promiseTitle: "Un espacio tranquilo para contenido.", promise: "DeskHaven no oculta archivos: ayuda a entender sus relaciones.", features: [["Vista general primero", "Panel de archivos, relaciones, cifrado y almacenamiento."], ["Bóveda de archivos", "Gestiona archivos y metadatos locales con calma."], ["Mapa de relaciones", "Ve conexiones entre archivos, etiquetas y proyectos."], ["Privacidad y control", "Claves, importación, exportación y cifrado claros."], ["Automatización discreta", "El orden sucede en segundo plano."]], principles: [["Local-first", "Los archivos importantes se tratan localmente por defecto."], ["Controlado", "El usuario sabe dónde están y cómo recuperarlos."], ["Relacional", "Las conexiones se entienden."], ["Baja fricción", "Organizar no se vuelve otra carga."]] },
    adhd: { ...siteCopy.en.adhd, eyebrow: "ADHD Focus Timer / Foco suave", title: "Concentrarse sin juzgar la atención.", intro: "Herramienta inmersiva con respiración, conteo hacia adelante, partículas, Idea Fridge y privacidad local.", status: "Próximamente", promiseTitle: "El foco no debería sentirse como castigo de cuenta regresiva.", promise: "Ayuda a entrar, sostenerse y recibir distracciones sin culpa.", features: [["Bajar el ruido", "La introducción reduce la resistencia inicial."], ["Preparar", "Duración, sonido, idioma y respiración se eligen antes."], ["Transición respiratoria", "Una guía breve ayuda a cambiar de estado."], ["Conteo hacia adelante", "El tiempo se acumula sin sensación de fracaso."], ["Idea Fridge", "Las ideas repentinas pueden esperar."], ["Cierre suave", "Terminar registra un logro real, no un juicio."], ["Soporte y privacidad", "Datos mínimos y local-first."]] },
  },
};

export function getSiteCopy(locale: Locale) {
  if (locale === "zh") return siteCopy.zh;
  return {
    ...(localized[locale] ?? siteCopy.en),
    ...(productLocaleCopy[locale] ?? {}),
  };
}
